// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssn/pdfservice/v1alpha1/pdfservice.proto

package pdfservice // import "github.com/e-conomic/proto/ssn/pdfservice/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RasterizePdfRequest_Format int32

const (
	RasterizePdfRequest_PNG RasterizePdfRequest_Format = 0
)

var RasterizePdfRequest_Format_name = map[int32]string{
	0: "PNG",
}
var RasterizePdfRequest_Format_value = map[string]int32{
	"PNG": 0,
}

func (x RasterizePdfRequest_Format) String() string {
	return proto.EnumName(RasterizePdfRequest_Format_name, int32(x))
}
func (RasterizePdfRequest_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pdfservice_c81c866ad2700da0, []int{0, 0}
}

type RasterizePdfRequest struct {
	Data                 []byte                     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Dpi                  uint32                     `protobuf:"varint,2,opt,name=dpi,proto3" json:"dpi,omitempty"`
	Format               RasterizePdfRequest_Format `protobuf:"varint,3,opt,name=format,proto3,enum=pdfservice.RasterizePdfRequest_Format" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RasterizePdfRequest) Reset()         { *m = RasterizePdfRequest{} }
func (m *RasterizePdfRequest) String() string { return proto.CompactTextString(m) }
func (*RasterizePdfRequest) ProtoMessage()    {}
func (*RasterizePdfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pdfservice_c81c866ad2700da0, []int{0}
}
func (m *RasterizePdfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RasterizePdfRequest.Unmarshal(m, b)
}
func (m *RasterizePdfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RasterizePdfRequest.Marshal(b, m, deterministic)
}
func (dst *RasterizePdfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RasterizePdfRequest.Merge(dst, src)
}
func (m *RasterizePdfRequest) XXX_Size() int {
	return xxx_messageInfo_RasterizePdfRequest.Size(m)
}
func (m *RasterizePdfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RasterizePdfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RasterizePdfRequest proto.InternalMessageInfo

func (m *RasterizePdfRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RasterizePdfRequest) GetDpi() uint32 {
	if m != nil {
		return m.Dpi
	}
	return 0
}

func (m *RasterizePdfRequest) GetFormat() RasterizePdfRequest_Format {
	if m != nil {
		return m.Format
	}
	return RasterizePdfRequest_PNG
}

type RasterizePdfResponse struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RasterizePdfResponse) Reset()         { *m = RasterizePdfResponse{} }
func (m *RasterizePdfResponse) String() string { return proto.CompactTextString(m) }
func (*RasterizePdfResponse) ProtoMessage()    {}
func (*RasterizePdfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pdfservice_c81c866ad2700da0, []int{1}
}
func (m *RasterizePdfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RasterizePdfResponse.Unmarshal(m, b)
}
func (m *RasterizePdfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RasterizePdfResponse.Marshal(b, m, deterministic)
}
func (dst *RasterizePdfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RasterizePdfResponse.Merge(dst, src)
}
func (m *RasterizePdfResponse) XXX_Size() int {
	return xxx_messageInfo_RasterizePdfResponse.Size(m)
}
func (m *RasterizePdfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RasterizePdfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RasterizePdfResponse proto.InternalMessageInfo

func (m *RasterizePdfResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RasterizePdfResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RasterizePdfRequest)(nil), "pdfservice.RasterizePdfRequest")
	proto.RegisterType((*RasterizePdfResponse)(nil), "pdfservice.RasterizePdfResponse")
	proto.RegisterEnum("pdfservice.RasterizePdfRequest_Format", RasterizePdfRequest_Format_name, RasterizePdfRequest_Format_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PdfServiceClient is the client API for PdfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PdfServiceClient interface {
	RasterizePdf(ctx context.Context, in *RasterizePdfRequest, opts ...grpc.CallOption) (PdfService_RasterizePdfClient, error)
}

type pdfServiceClient struct {
	cc *grpc.ClientConn
}

func NewPdfServiceClient(cc *grpc.ClientConn) PdfServiceClient {
	return &pdfServiceClient{cc}
}

func (c *pdfServiceClient) RasterizePdf(ctx context.Context, in *RasterizePdfRequest, opts ...grpc.CallOption) (PdfService_RasterizePdfClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PdfService_serviceDesc.Streams[0], "/pdfservice.PdfService/RasterizePdf", opts...)
	if err != nil {
		return nil, err
	}
	x := &pdfServiceRasterizePdfClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PdfService_RasterizePdfClient interface {
	Recv() (*RasterizePdfResponse, error)
	grpc.ClientStream
}

type pdfServiceRasterizePdfClient struct {
	grpc.ClientStream
}

func (x *pdfServiceRasterizePdfClient) Recv() (*RasterizePdfResponse, error) {
	m := new(RasterizePdfResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PdfServiceServer is the server API for PdfService service.
type PdfServiceServer interface {
	RasterizePdf(*RasterizePdfRequest, PdfService_RasterizePdfServer) error
}

func RegisterPdfServiceServer(s *grpc.Server, srv PdfServiceServer) {
	s.RegisterService(&_PdfService_serviceDesc, srv)
}

func _PdfService_RasterizePdf_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RasterizePdfRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PdfServiceServer).RasterizePdf(m, &pdfServiceRasterizePdfServer{stream})
}

type PdfService_RasterizePdfServer interface {
	Send(*RasterizePdfResponse) error
	grpc.ServerStream
}

type pdfServiceRasterizePdfServer struct {
	grpc.ServerStream
}

func (x *pdfServiceRasterizePdfServer) Send(m *RasterizePdfResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PdfService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pdfservice.PdfService",
	HandlerType: (*PdfServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RasterizePdf",
			Handler:       _PdfService_RasterizePdf_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ssn/pdfservice/v1alpha1/pdfservice.proto",
}

func init() {
	proto.RegisterFile("ssn/pdfservice/v1alpha1/pdfservice.proto", fileDescriptor_pdfservice_c81c866ad2700da0)
}

var fileDescriptor_pdfservice_c81c866ad2700da0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x97, 0x55, 0x2b, 0x3c, 0x36, 0x99, 0x71, 0x87, 0xe2, 0xc5, 0xd2, 0x83, 0xf4, 0x62,
	0xeb, 0xe6, 0x51, 0xfc, 0x81, 0x07, 0xbd, 0x49, 0x89, 0x78, 0xf1, 0x96, 0x25, 0xaf, 0x2e, 0x60,
	0x9b, 0xd8, 0x64, 0x43, 0xfc, 0x23, 0xfc, 0x9b, 0xc5, 0x54, 0x6c, 0x05, 0xc7, 0x6e, 0x2f, 0x1f,
	0xbe, 0xef, 0x9b, 0x0f, 0x09, 0xa4, 0xd6, 0xd6, 0xb9, 0x91, 0xa5, 0xc5, 0x66, 0xad, 0x04, 0xe6,
	0xeb, 0x19, 0x7f, 0x35, 0x4b, 0x3e, 0xeb, 0xb1, 0xcc, 0x34, 0xda, 0x69, 0x0a, 0x1d, 0x49, 0x3e,
	0x09, 0x1c, 0x32, 0x6e, 0x1d, 0x36, 0xea, 0x03, 0x0b, 0x59, 0x32, 0x7c, 0x5b, 0xa1, 0x75, 0x94,
	0xc2, 0x8e, 0xe4, 0x8e, 0x47, 0x24, 0x26, 0xe9, 0x88, 0xf9, 0x99, 0x4e, 0x20, 0x90, 0x46, 0x45,
	0xc3, 0x98, 0xa4, 0x63, 0xf6, 0x3d, 0xd2, 0x2b, 0x08, 0x4b, 0xdd, 0x54, 0xdc, 0x45, 0x41, 0x4c,
	0xd2, 0xfd, 0xf9, 0x49, 0xd6, 0xbb, 0xec, 0x9f, 0xda, 0xec, 0xce, 0xa7, 0xd9, 0xcf, 0x56, 0x72,
	0x00, 0x61, 0x4b, 0xe8, 0x1e, 0x04, 0xc5, 0xc3, 0xfd, 0x64, 0x90, 0xdc, 0xc0, 0xf4, 0xef, 0xa2,
	0x35, 0xba, 0xb6, 0x48, 0xa7, 0xb0, 0xab, 0x6a, 0x89, 0xef, 0xde, 0x68, 0xcc, 0xda, 0xc3, 0xaf,
	0xe6, 0xb0, 0xd3, 0x9c, 0x0b, 0x80, 0x42, 0x96, 0x8f, 0xad, 0x05, 0x7d, 0x82, 0x51, 0xbf, 0x8f,
	0x1e, 0x6f, 0x51, 0x3c, 0x8a, 0x37, 0x07, 0x5a, 0x95, 0x64, 0x70, 0x46, 0x6e, 0xaf, 0x9f, 0x2f,
	0x5f, 0x94, 0x5b, 0xae, 0x16, 0x99, 0xd0, 0x55, 0x8e, 0xa7, 0x42, 0xd7, 0xba, 0x52, 0x22, 0xf7,
	0x2f, 0x9c, 0x6f, 0xf8, 0x8a, 0x8b, 0x8e, 0x2d, 0x42, 0x9f, 0x3c, 0xff, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x51, 0xeb, 0xce, 0x13, 0xb7, 0x01, 0x00, 0x00,
}
