steps:
  - name: "python:3.7-buster"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install twine
        python setup.py bdist_wheel
        twine upload --repository-url https://europe-west4-python.pkg.dev/dev-vml-cm/vml-apis-python/ dist/*
    id: deploy
