steps:
  - id: deploy-python
    name: "python:3.7-buster"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$TAG_NAME" ] ; then
          python setup.py bdist_wheel
          pip install twine keyrings.google-artifactregistry-auth
          twine upload --repository-url https://europe-west4-python.pkg.dev/dev-vml-cm/vml-apis-python/ dist/*
        else
          TAG_NAME="v0.0.0"
          python setup.py bdist_wheel
        fi
    env:
      - 'TAG_NAME=$TAG_NAME'

  - id: deploy-csharp
    name: "bitnami/dotnet-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cp vmlapis.csproj gen/csharp
        cd gen/csharp
        if [ "$TAG_NAME"  ] ; then
          export TAG_NAME=${TAG_NAME:1} 
          dotnet pack -o . -c Release
          dotnet nuget push vmlapis.$$TAG_NAME.nupkg --source https://api.nuget.org/v3/index.json --api-key $$NUGET_API_KEY
        else 
          export TAG_NAME=0.0.0
          dotnet pack -o . -c Release
        fi
    env:
      - 'TAG_NAME=$TAG_NAME'
    waitFor: ['-']
    secretEnv: ['NUGET_API_KEY']

  - id: deploy-java
    name: "maven:3.6.3-jdk-8"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cp -R gen/java java-package/src/main/java
        cd java-package
        if [ "$TAG_NAME" ] ; then
          export TAG_NAME=${TAG_NAME:1}
          mvn deploy
        else
          export TAG_NAME=0.0.0
          mvn package
        fi
    env:
      - 'TAG_NAME=$TAG_NAME'
    waitFor: ['-']
  - id: test-go
    name: 'golang'
    entrypoint: "bash"
    args:
      - "-c"
      - |
        mkdir gotest
        cp -R examples/go/AnnotateDocumentExample gotest/AnnotateDocumentExample
        cp -R examples/go/CreateDatasetExample gotest/CreateDatasetExample
        cp -R examples/go/RasterizePdfExample gotest/RasterizePdfExample
        sed -i 's/commit/$COMMIT_SHA' go.mod.example
        cp go.mod.example gotest/AnnotateDocumentExample/go.mod
        cp go.mod.example gotest/CreateDatasetExample/go.mod
        cp go.mod.example gotest/RasterizePdfExample/go.mod
        cd gotest/AnnotateDocumentExample
        go mod tidy
        go build
        cd ../CreateDatasetExample
        go mod tidy
        go build
        cd ../RasterizePdfExample
        go mod tidy
        go build

availableSecrets:
  secretManager:
    - versionName: projects/161107618804/secrets/nuget-api-key/versions/latest
      env: 'NUGET_API_KEY'
