steps:
#  - id: deploy
#    name: "python:3.7-buster"
#    entrypoint: "bash"
#    args:
#      - "-c"
#      - |
#        if [ "$TAG_NAME" ] ; then
#          pip install twine keyrings.google-artifactregistry-auth
#          python setup.py bdist_wheel
#          twine upload --repository-url https://europe-west4-python.pkg.dev/dev-vml-cm/vml-apis-python/ dist/*
#        fi
#    env:
#      - "TAG_NAME=${TAG_NAME}"
#
#  - id: deploy-csharp
#    name: "bitnami/dotnet-sdk"
#    entrypoint: "bash"
#    args:
#      - "-c"
#      - |
#        if [ "$TAG_NAME" ] ; then
#          apt-get update -y
#          apt-get install -y nuget
#          cd gen/csharp
#          dotnet pack -c Release
#          nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $NUGET_API_KEY
#        fi

  - id: deploy-java
    name: "maven:3.6.3-jdk-8"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$TAG_NAME" ] ; then
          cp -R gen/java java-package/src/main/java
          cd java-package
          mvn deploy
        fi