steps:
#  - id: deploy
#    name: "python:3.7-buster"
#    entrypoint: "bash"
#    args:
#      - "-c"
#      - |
#        if [ "$TAG_NAME" ] ; then
#          pip install twine keyrings.google-artifactregistry-auth
#          python setup.py bdist_wheel
#          twine upload --repository-url https://europe-west4-python.pkg.dev/dev-vml-cm/vml-apis-python/ dist/*
#        fi
#    env:
#      - "TAG_NAME=${TAG_NAME}"
#
  - id: deploy-csharp
    name: "bitnami/dotnet-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ 0 ] ; then
          export TAG_NAME=1.0.3
          cp vmlapis.csproj gen/csharp
          cd gen/csharp
          dotnet pack -o . -c Release
          dotnet nuget push vmlapis.$$TAG_NAME.nupkg --source https://api.nuget.org/v3/index.json --api-key $$NUGET_API_KEY
        fi
    secretEnv: ['NUGET_API_KEY']

#  - id: deploy-java
#    name: "maven:3.6.3-jdk-8"
#    entrypoint: "bash"
#    args:
#      - "-c"
#      - |
#        if [ "$TAG_NAME" ] ; then
#          cp -R gen/java java-package/src/main/java
#          cd java-package
#          mvn deploy
#        fi
availableSecrets:
  secretManager:
    - versionName: projects/161107618804/secrets/nuget-api-key/versions/latest
      env: 'NUGET_API_KEY'