steps:
- name: "python:3.7-buster"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [ "$TAG_NAME" ] ; then
      pip install twine
      # Replace asgt imports based on proto structure with package name.
      # replace for asgt modules with no version(eg. v1alpha)
      sed -i 's/from asgt/from vml_proto.asgt/' gen/python/asgt/*/*.py
      # replace for asgt modules with version(eg. v1alpha)
      sed -i 's/from asgt/from vml_proto.asgt/' gen/python/asgt/*/*/*.py
      # replace for ssn modules with no version(eg. v1alpha)
      sed -i 's/from ssn/from vml_proto.ssn/' gen/python/ssn/*/*.py
      # replace for ssn modules with version(eg. v1alpha)
      sed -i 's/from ssn/from vml_proto.ssn/' gen/python/ssn/*/*/*.py
      python setup.py bdist_wheel
      twine upload --repository-url https://vismaartifactory.jfrog.io/vismaartifactory/api/pypi/vml-pypi -u vml-rw -p $$ARTIFACTORY_PW dist/*
    fi
  env:
    - 'TAG_NAME=${TAG_NAME}'
  secretEnv:
    - 'ARTIFACTORY_PW'
  id: deploy

secrets:
- kmsKeyName: projects/dev-vml-cm/locations/global/keyRings/builder/cryptoKeys/artifactory-pw
  secretEnv:
    ARTIFACTORY_PW: CiQABn9jLUW+LqR7sIGt+qNrDfIizwL4UNyumnqsi5I9/ofLHj0ScgBPNwwDR4MZUFeoGyz5P/OLqlGE27q0vayqbXUyd3AM9Mka2GMuqbGaJSpQvAxTEz3/vanIZLRJ3NPA5SRDzJraulDl7UaDm4F//N6UNI3DuPNSnfNqLPtL41ko67wTSfJgattedTz8xxjVWVnyUqwpLw==
