// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssn/mlservice/v1alpha1/mlservice.proto

package mlservice // import "github.com/e-conomic/proto/ssn/mlservice/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1alpha1 "github.com/e-conomic/proto/ssn/ocrservice/v1alpha1"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PredictedField struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Confidence           float32  `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictedField) Reset()         { *m = PredictedField{} }
func (m *PredictedField) String() string { return proto.CompactTextString(m) }
func (*PredictedField) ProtoMessage()    {}
func (*PredictedField) Descriptor() ([]byte, []int) {
	return fileDescriptor_mlservice_8a7f019d1111b368, []int{0}
}
func (m *PredictedField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictedField.Unmarshal(m, b)
}
func (m *PredictedField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictedField.Marshal(b, m, deterministic)
}
func (dst *PredictedField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictedField.Merge(dst, src)
}
func (m *PredictedField) XXX_Size() int {
	return xxx_messageInfo_PredictedField.Size(m)
}
func (m *PredictedField) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictedField.DiscardUnknown(m)
}

var xxx_messageInfo_PredictedField proto.InternalMessageInfo

func (m *PredictedField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PredictedField) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type MlRequest struct {
	OcrResponses         []*v1alpha1.OcrScanImageResponse `protobuf:"bytes,1,rep,name=ocrResponses,proto3" json:"ocrResponses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *MlRequest) Reset()         { *m = MlRequest{} }
func (m *MlRequest) String() string { return proto.CompactTextString(m) }
func (*MlRequest) ProtoMessage()    {}
func (*MlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mlservice_8a7f019d1111b368, []int{1}
}
func (m *MlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlRequest.Unmarshal(m, b)
}
func (m *MlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlRequest.Marshal(b, m, deterministic)
}
func (dst *MlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlRequest.Merge(dst, src)
}
func (m *MlRequest) XXX_Size() int {
	return xxx_messageInfo_MlRequest.Size(m)
}
func (m *MlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MlRequest proto.InternalMessageInfo

func (m *MlRequest) GetOcrResponses() []*v1alpha1.OcrScanImageResponse {
	if m != nil {
		return m.OcrResponses
	}
	return nil
}

type MlResponse struct {
	OrderDate                *PredictedField   `protobuf:"bytes,1,opt,name=orderDate,proto3" json:"orderDate,omitempty"`
	PaymentDueDate           *PredictedField   `protobuf:"bytes,2,opt,name=paymentDueDate,proto3" json:"paymentDueDate,omitempty"`
	Currency                 *PredictedField   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	TotalVat                 *PredictedField   `protobuf:"bytes,4,opt,name=totalVat,proto3" json:"totalVat,omitempty"`
	TotalInclVat             *PredictedField   `protobuf:"bytes,5,opt,name=totalInclVat,proto3" json:"totalInclVat,omitempty"`
	TotalExclVat             *PredictedField   `protobuf:"bytes,6,opt,name=totalExclVat,proto3" json:"totalExclVat,omitempty"`
	SupplierCorporateId      []*PredictedField `protobuf:"bytes,7,rep,name=supplierCorporateId,proto3" json:"supplierCorporateId,omitempty"`
	SupplierCountryCode      *PredictedField   `protobuf:"bytes,8,opt,name=supplierCountryCode,proto3" json:"supplierCountryCode,omitempty"`
	DocumentType             *PredictedField   `protobuf:"bytes,9,opt,name=documentType,proto3" json:"documentType,omitempty"`
	PaymentMethod            *PredictedField   `protobuf:"bytes,10,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	CreditCardLastFourDigits *PredictedField   `protobuf:"bytes,11,opt,name=creditCardLastFourDigits,proto3" json:"creditCardLastFourDigits,omitempty"`
	InvoiceNumber            *PredictedField   `protobuf:"bytes,17,opt,name=invoiceNumber,proto3" json:"invoiceNumber,omitempty"`
	// Types that are valid to be assigned to OcrLine:
	//	*MlResponse_OcrLineDk_
	//	*MlResponse_OcrLineSe_
	//	*MlResponse_OcrLineNo_
	//	*MlResponse_OcrLineFi_
	//	*MlResponse_OcrLineNl_
	OcrLine              isMlResponse_OcrLine `protobuf_oneof:"ocrLine"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MlResponse) Reset()         { *m = MlResponse{} }
func (m *MlResponse) String() string { return proto.CompactTextString(m) }
func (*MlResponse) ProtoMessage()    {}
func (*MlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mlservice_8a7f019d1111b368, []int{2}
}
func (m *MlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse.Unmarshal(m, b)
}
func (m *MlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse.Marshal(b, m, deterministic)
}
func (dst *MlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse.Merge(dst, src)
}
func (m *MlResponse) XXX_Size() int {
	return xxx_messageInfo_MlResponse.Size(m)
}
func (m *MlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse proto.InternalMessageInfo

func (m *MlResponse) GetOrderDate() *PredictedField {
	if m != nil {
		return m.OrderDate
	}
	return nil
}

func (m *MlResponse) GetPaymentDueDate() *PredictedField {
	if m != nil {
		return m.PaymentDueDate
	}
	return nil
}

func (m *MlResponse) GetCurrency() *PredictedField {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *MlResponse) GetTotalVat() *PredictedField {
	if m != nil {
		return m.TotalVat
	}
	return nil
}

func (m *MlResponse) GetTotalInclVat() *PredictedField {
	if m != nil {
		return m.TotalInclVat
	}
	return nil
}

func (m *MlResponse) GetTotalExclVat() *PredictedField {
	if m != nil {
		return m.TotalExclVat
	}
	return nil
}

func (m *MlResponse) GetSupplierCorporateId() []*PredictedField {
	if m != nil {
		return m.SupplierCorporateId
	}
	return nil
}

func (m *MlResponse) GetSupplierCountryCode() *PredictedField {
	if m != nil {
		return m.SupplierCountryCode
	}
	return nil
}

func (m *MlResponse) GetDocumentType() *PredictedField {
	if m != nil {
		return m.DocumentType
	}
	return nil
}

func (m *MlResponse) GetPaymentMethod() *PredictedField {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

func (m *MlResponse) GetCreditCardLastFourDigits() *PredictedField {
	if m != nil {
		return m.CreditCardLastFourDigits
	}
	return nil
}

func (m *MlResponse) GetInvoiceNumber() *PredictedField {
	if m != nil {
		return m.InvoiceNumber
	}
	return nil
}

type isMlResponse_OcrLine interface {
	isMlResponse_OcrLine()
}

type MlResponse_OcrLineDk_ struct {
	OcrLineDk *MlResponse_OcrLineDk `protobuf:"bytes,12,opt,name=ocrLineDk,proto3,oneof"`
}

type MlResponse_OcrLineSe_ struct {
	OcrLineSe *MlResponse_OcrLineSe `protobuf:"bytes,13,opt,name=ocrLineSe,proto3,oneof"`
}

type MlResponse_OcrLineNo_ struct {
	OcrLineNo *MlResponse_OcrLineNo `protobuf:"bytes,14,opt,name=ocrLineNo,proto3,oneof"`
}

type MlResponse_OcrLineFi_ struct {
	OcrLineFi *MlResponse_OcrLineFi `protobuf:"bytes,15,opt,name=ocrLineFi,proto3,oneof"`
}

type MlResponse_OcrLineNl_ struct {
	OcrLineNl *MlResponse_OcrLineNl `protobuf:"bytes,16,opt,name=ocrLineNl,proto3,oneof"`
}

func (*MlResponse_OcrLineDk_) isMlResponse_OcrLine() {}

func (*MlResponse_OcrLineSe_) isMlResponse_OcrLine() {}

func (*MlResponse_OcrLineNo_) isMlResponse_OcrLine() {}

func (*MlResponse_OcrLineFi_) isMlResponse_OcrLine() {}

func (*MlResponse_OcrLineNl_) isMlResponse_OcrLine() {}

func (m *MlResponse) GetOcrLine() isMlResponse_OcrLine {
	if m != nil {
		return m.OcrLine
	}
	return nil
}

func (m *MlResponse) GetOcrLineDk() *MlResponse_OcrLineDk {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineDk_); ok {
		return x.OcrLineDk
	}
	return nil
}

func (m *MlResponse) GetOcrLineSe() *MlResponse_OcrLineSe {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineSe_); ok {
		return x.OcrLineSe
	}
	return nil
}

func (m *MlResponse) GetOcrLineNo() *MlResponse_OcrLineNo {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineNo_); ok {
		return x.OcrLineNo
	}
	return nil
}

func (m *MlResponse) GetOcrLineFi() *MlResponse_OcrLineFi {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineFi_); ok {
		return x.OcrLineFi
	}
	return nil
}

func (m *MlResponse) GetOcrLineNl() *MlResponse_OcrLineNl {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineNl_); ok {
		return x.OcrLineNl
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MlResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MlResponse_OneofMarshaler, _MlResponse_OneofUnmarshaler, _MlResponse_OneofSizer, []interface{}{
		(*MlResponse_OcrLineDk_)(nil),
		(*MlResponse_OcrLineSe_)(nil),
		(*MlResponse_OcrLineNo_)(nil),
		(*MlResponse_OcrLineFi_)(nil),
		(*MlResponse_OcrLineNl_)(nil),
	}
}

func _MlResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MlResponse)
	// ocrLine
	switch x := m.OcrLine.(type) {
	case *MlResponse_OcrLineDk_:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OcrLineDk); err != nil {
			return err
		}
	case *MlResponse_OcrLineSe_:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OcrLineSe); err != nil {
			return err
		}
	case *MlResponse_OcrLineNo_:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OcrLineNo); err != nil {
			return err
		}
	case *MlResponse_OcrLineFi_:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OcrLineFi); err != nil {
			return err
		}
	case *MlResponse_OcrLineNl_:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OcrLineNl); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MlResponse.OcrLine has unexpected type %T", x)
	}
	return nil
}

func _MlResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MlResponse)
	switch tag {
	case 12: // ocrLine.ocrLineDk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MlResponse_OcrLineDk)
		err := b.DecodeMessage(msg)
		m.OcrLine = &MlResponse_OcrLineDk_{msg}
		return true, err
	case 13: // ocrLine.ocrLineSe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MlResponse_OcrLineSe)
		err := b.DecodeMessage(msg)
		m.OcrLine = &MlResponse_OcrLineSe_{msg}
		return true, err
	case 14: // ocrLine.ocrLineNo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MlResponse_OcrLineNo)
		err := b.DecodeMessage(msg)
		m.OcrLine = &MlResponse_OcrLineNo_{msg}
		return true, err
	case 15: // ocrLine.ocrLineFi
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MlResponse_OcrLineFi)
		err := b.DecodeMessage(msg)
		m.OcrLine = &MlResponse_OcrLineFi_{msg}
		return true, err
	case 16: // ocrLine.ocrLineNl
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MlResponse_OcrLineNl)
		err := b.DecodeMessage(msg)
		m.OcrLine = &MlResponse_OcrLineNl_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MlResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MlResponse)
	// ocrLine
	switch x := m.OcrLine.(type) {
	case *MlResponse_OcrLineDk_:
		s := proto.Size(x.OcrLineDk)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MlResponse_OcrLineSe_:
		s := proto.Size(x.OcrLineSe)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MlResponse_OcrLineNo_:
		s := proto.Size(x.OcrLineNo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MlResponse_OcrLineFi_:
		s := proto.Size(x.OcrLineFi)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MlResponse_OcrLineNl_:
		s := proto.Size(x.OcrLineNl)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MlResponse_OcrLineDk struct {
	Type                 *PredictedField `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PaymentId            *PredictedField `protobuf:"bytes,2,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	CreditorId           *PredictedField `protobuf:"bytes,3,opt,name=creditorId,proto3" json:"creditorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineDk) Reset()         { *m = MlResponse_OcrLineDk{} }
func (m *MlResponse_OcrLineDk) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineDk) ProtoMessage()    {}
func (*MlResponse_OcrLineDk) Descriptor() ([]byte, []int) {
	return fileDescriptor_mlservice_8a7f019d1111b368, []int{2, 0}
}
func (m *MlResponse_OcrLineDk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineDk.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineDk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineDk.Marshal(b, m, deterministic)
}
func (dst *MlResponse_OcrLineDk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineDk.Merge(dst, src)
}
func (m *MlResponse_OcrLineDk) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineDk.Size(m)
}
func (m *MlResponse_OcrLineDk) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineDk.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineDk proto.InternalMessageInfo

func (m *MlResponse_OcrLineDk) GetType() *PredictedField {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *MlResponse_OcrLineDk) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func (m *MlResponse_OcrLineDk) GetCreditorId() *PredictedField {
	if m != nil {
		return m.CreditorId
	}
	return nil
}

type MlResponse_OcrLineSe struct {
	PaymentId            *PredictedField `protobuf:"bytes,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	BankgiroCreditorId   *PredictedField `protobuf:"bytes,2,opt,name=bankgiroCreditorId,proto3" json:"bankgiroCreditorId,omitempty"`
	PlusgiroCreditorId   *PredictedField `protobuf:"bytes,3,opt,name=plusgiroCreditorId,proto3" json:"plusgiroCreditorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineSe) Reset()         { *m = MlResponse_OcrLineSe{} }
func (m *MlResponse_OcrLineSe) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineSe) ProtoMessage()    {}
func (*MlResponse_OcrLineSe) Descriptor() ([]byte, []int) {
	return fileDescriptor_mlservice_8a7f019d1111b368, []int{2, 1}
}
func (m *MlResponse_OcrLineSe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineSe.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineSe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineSe.Marshal(b, m, deterministic)
}
func (dst *MlResponse_OcrLineSe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineSe.Merge(dst, src)
}
func (m *MlResponse_OcrLineSe) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineSe.Size(m)
}
func (m *MlResponse_OcrLineSe) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineSe.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineSe proto.InternalMessageInfo

func (m *MlResponse_OcrLineSe) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func (m *MlResponse_OcrLineSe) GetBankgiroCreditorId() *PredictedField {
	if m != nil {
		return m.BankgiroCreditorId
	}
	return nil
}

func (m *MlResponse_OcrLineSe) GetPlusgiroCreditorId() *PredictedField {
	if m != nil {
		return m.PlusgiroCreditorId
	}
	return nil
}

type MlResponse_OcrLineNo struct {
	PaymentId            *PredictedField `protobuf:"bytes,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineNo) Reset()         { *m = MlResponse_OcrLineNo{} }
func (m *MlResponse_OcrLineNo) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineNo) ProtoMessage()    {}
func (*MlResponse_OcrLineNo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mlservice_8a7f019d1111b368, []int{2, 2}
}
func (m *MlResponse_OcrLineNo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineNo.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineNo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineNo.Marshal(b, m, deterministic)
}
func (dst *MlResponse_OcrLineNo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineNo.Merge(dst, src)
}
func (m *MlResponse_OcrLineNo) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineNo.Size(m)
}
func (m *MlResponse_OcrLineNo) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineNo.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineNo proto.InternalMessageInfo

func (m *MlResponse_OcrLineNo) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

type MlResponse_OcrLineNl struct {
	PaymentId            *PredictedField `protobuf:"bytes,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineNl) Reset()         { *m = MlResponse_OcrLineNl{} }
func (m *MlResponse_OcrLineNl) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineNl) ProtoMessage()    {}
func (*MlResponse_OcrLineNl) Descriptor() ([]byte, []int) {
	return fileDescriptor_mlservice_8a7f019d1111b368, []int{2, 3}
}
func (m *MlResponse_OcrLineNl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineNl.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineNl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineNl.Marshal(b, m, deterministic)
}
func (dst *MlResponse_OcrLineNl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineNl.Merge(dst, src)
}
func (m *MlResponse_OcrLineNl) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineNl.Size(m)
}
func (m *MlResponse_OcrLineNl) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineNl.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineNl proto.InternalMessageInfo

func (m *MlResponse_OcrLineNl) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

type MlResponse_OcrLineFi struct {
	PaymentId            *PredictedField `protobuf:"bytes,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineFi) Reset()         { *m = MlResponse_OcrLineFi{} }
func (m *MlResponse_OcrLineFi) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineFi) ProtoMessage()    {}
func (*MlResponse_OcrLineFi) Descriptor() ([]byte, []int) {
	return fileDescriptor_mlservice_8a7f019d1111b368, []int{2, 4}
}
func (m *MlResponse_OcrLineFi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineFi.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineFi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineFi.Marshal(b, m, deterministic)
}
func (dst *MlResponse_OcrLineFi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineFi.Merge(dst, src)
}
func (m *MlResponse_OcrLineFi) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineFi.Size(m)
}
func (m *MlResponse_OcrLineFi) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineFi.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineFi proto.InternalMessageInfo

func (m *MlResponse_OcrLineFi) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func init() {
	proto.RegisterType((*PredictedField)(nil), "mlservice.PredictedField")
	proto.RegisterType((*MlRequest)(nil), "mlservice.MlRequest")
	proto.RegisterType((*MlResponse)(nil), "mlservice.MlResponse")
	proto.RegisterType((*MlResponse_OcrLineDk)(nil), "mlservice.MlResponse.OcrLineDk")
	proto.RegisterType((*MlResponse_OcrLineSe)(nil), "mlservice.MlResponse.OcrLineSe")
	proto.RegisterType((*MlResponse_OcrLineNo)(nil), "mlservice.MlResponse.OcrLineNo")
	proto.RegisterType((*MlResponse_OcrLineNl)(nil), "mlservice.MlResponse.OcrLineNl")
	proto.RegisterType((*MlResponse_OcrLineFi)(nil), "mlservice.MlResponse.OcrLineFi")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MlServiceClient is the client API for MlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MlServiceClient interface {
	GetPrediction(ctx context.Context, in *MlRequest, opts ...grpc.CallOption) (*MlResponse, error)
}

type mlServiceClient struct {
	cc *grpc.ClientConn
}

func NewMlServiceClient(cc *grpc.ClientConn) MlServiceClient {
	return &mlServiceClient{cc}
}

func (c *mlServiceClient) GetPrediction(ctx context.Context, in *MlRequest, opts ...grpc.CallOption) (*MlResponse, error) {
	out := new(MlResponse)
	err := c.cc.Invoke(ctx, "/mlservice.MlService/GetPrediction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlServiceServer is the server API for MlService service.
type MlServiceServer interface {
	GetPrediction(context.Context, *MlRequest) (*MlResponse, error)
}

func RegisterMlServiceServer(s *grpc.Server, srv MlServiceServer) {
	s.RegisterService(&_MlService_serviceDesc, srv)
}

func _MlService_GetPrediction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlServiceServer).GetPrediction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mlservice.MlService/GetPrediction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlServiceServer).GetPrediction(ctx, req.(*MlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mlservice.MlService",
	HandlerType: (*MlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrediction",
			Handler:    _MlService_GetPrediction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssn/mlservice/v1alpha1/mlservice.proto",
}

func init() {
	proto.RegisterFile("ssn/mlservice/v1alpha1/mlservice.proto", fileDescriptor_mlservice_8a7f019d1111b368)
}

var fileDescriptor_mlservice_8a7f019d1111b368 = []byte{
	// 657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x5f, 0x6f, 0xd3, 0x3c,
	0x14, 0xc6, 0xd7, 0xfd, 0x8f, 0xb7, 0xee, 0x7d, 0x31, 0x43, 0x32, 0xbd, 0x80, 0xaa, 0x17, 0xa8,
	0x37, 0x6b, 0xb5, 0x21, 0x84, 0xd0, 0x34, 0x26, 0xd6, 0x12, 0xa8, 0xb6, 0x15, 0x48, 0x81, 0x0b,
	0xee, 0x52, 0xe7, 0xd0, 0x59, 0x4b, 0x7d, 0x82, 0xe3, 0x54, 0xf4, 0x4b, 0xf1, 0x71, 0xb8, 0xe0,
	0xd3, 0xa0, 0x24, 0x5d, 0xe3, 0x96, 0x82, 0xcb, 0xc4, 0x5d, 0x73, 0xf4, 0xfc, 0x9e, 0x3e, 0x27,
	0x3e, 0xb6, 0x43, 0x1e, 0xc5, 0xb1, 0x6c, 0x0e, 0xc3, 0x18, 0xd4, 0x48, 0x70, 0x68, 0x8e, 0x0e,
	0xfd, 0x30, 0xba, 0xf2, 0x0f, 0x8b, 0x52, 0x23, 0x52, 0xa8, 0x91, 0x3a, 0xd3, 0x42, 0xa5, 0x9e,
	0x22, 0xc8, 0xd5, 0x2f, 0x4c, 0x51, 0xcb, 0xa1, 0x9a, 0x4b, 0xf6, 0xde, 0x2a, 0x08, 0x04, 0xd7,
	0x10, 0xb8, 0x02, 0xc2, 0x80, 0xee, 0x93, 0x8d, 0x91, 0x1f, 0x26, 0xc0, 0x4a, 0xd5, 0x52, 0xdd,
	0xf1, 0xf2, 0x07, 0xfa, 0x80, 0x10, 0x8e, 0xf2, 0xb3, 0x08, 0x40, 0x72, 0x60, 0xab, 0xd5, 0x52,
	0x7d, 0xd5, 0x33, 0x2a, 0xb5, 0x77, 0xc4, 0xb9, 0x0c, 0x3d, 0xf8, 0x92, 0x40, 0xac, 0x69, 0x9b,
	0xec, 0x22, 0x57, 0x1e, 0xc4, 0x11, 0xca, 0x18, 0x62, 0x56, 0xaa, 0xae, 0xd5, 0x77, 0x8e, 0xaa,
	0x0d, 0xe3, 0xdf, 0xdf, 0x70, 0xd5, 0xe3, 0xbe, 0xec, 0x0c, 0xfd, 0x01, 0xdc, 0x08, 0xbd, 0x19,
	0xaa, 0xf6, 0xbd, 0x4c, 0x48, 0xea, 0x99, 0x3f, 0xd3, 0xa7, 0xc4, 0x41, 0x15, 0x80, 0x6a, 0xfb,
	0x3a, 0xcf, 0xb6, 0x73, 0x74, 0xbf, 0x51, 0xbc, 0x83, 0xd9, 0x2e, 0xbc, 0x42, 0x4b, 0x5f, 0x90,
	0xbd, 0xc8, 0x1f, 0x0f, 0x41, 0xea, 0x76, 0x02, 0x19, 0xbd, 0x6a, 0xa3, 0xe7, 0x00, 0xfa, 0x84,
	0x6c, 0xf3, 0x44, 0x29, 0x90, 0x7c, 0xcc, 0xd6, 0x6c, 0xf0, 0x54, 0x9a, 0x62, 0x1a, 0xb5, 0x1f,
	0x7e, 0xf4, 0x35, 0x5b, 0xb7, 0x62, 0x37, 0x52, 0x7a, 0x42, 0x76, 0xb3, 0xdf, 0x1d, 0xc9, 0x33,
	0x74, 0xc3, 0x86, 0xce, 0xc8, 0xa7, 0xf8, 0xcb, 0xaf, 0x39, 0xbe, 0xb9, 0x1c, 0x3e, 0x91, 0xd3,
	0x73, 0x72, 0x37, 0x4e, 0xa2, 0x28, 0x14, 0xa0, 0x5a, 0xa8, 0x22, 0x54, 0xbe, 0x86, 0x4e, 0xc0,
	0xb6, 0xb2, 0x35, 0xfc, 0x83, 0xcb, 0x22, 0x6a, 0xd6, 0x2c, 0x91, 0x5a, 0x8d, 0x5b, 0x18, 0x00,
	0xdb, 0xb6, 0x45, 0x5a, 0x44, 0xa5, 0x8d, 0x05, 0xc8, 0x93, 0x74, 0x61, 0xde, 0x8f, 0x23, 0x60,
	0x8e, 0xb5, 0x31, 0x53, 0x4e, 0x4f, 0x49, 0x79, 0xb2, 0xac, 0x97, 0xa0, 0xaf, 0x30, 0x60, 0xc4,
	0xc6, 0xcf, 0xea, 0xe9, 0x07, 0xc2, 0x78, 0x2a, 0xd0, 0x2d, 0x5f, 0x05, 0x17, 0x7e, 0xac, 0x5d,
	0x4c, 0x54, 0x5b, 0x0c, 0x84, 0x8e, 0xd9, 0x8e, 0xcd, 0xeb, 0xb7, 0x68, 0x9a, 0x4b, 0xc8, 0x11,
	0x0a, 0x0e, 0xdd, 0x64, 0xd8, 0x07, 0xc5, 0xee, 0x58, 0x73, 0xcd, 0xe8, 0xe9, 0x29, 0x71, 0x90,
	0xab, 0x0b, 0x21, 0xa1, 0x7d, 0xcd, 0x76, 0x33, 0xf8, 0xa1, 0x01, 0x17, 0x7b, 0x28, 0xdd, 0x75,
	0xb9, 0xec, 0xf5, 0x8a, 0x57, 0x30, 0x86, 0x41, 0x0f, 0x58, 0x79, 0x09, 0x83, 0x1e, 0x18, 0x06,
	0x3d, 0x30, 0x0c, 0xba, 0xc8, 0xf6, 0x96, 0x30, 0xe8, 0xa2, 0x61, 0xd0, 0x45, 0xc3, 0xc0, 0x15,
	0xec, 0xbf, 0x25, 0x0c, 0x5c, 0x61, 0x18, 0xb8, 0xc2, 0x4c, 0x10, 0xb2, 0xff, 0x97, 0x49, 0x10,
	0x9a, 0x09, 0xc2, 0xca, 0xb7, 0x12, 0x71, 0xa6, 0xaf, 0x87, 0x1e, 0x90, 0x75, 0x9d, 0x8e, 0x98,
	0xf5, 0x9c, 0xc9, 0x64, 0xe9, 0xd9, 0x34, 0x19, 0x95, 0x4e, 0x60, 0x3f, 0x5d, 0x0a, 0x2d, 0x7d,
	0x46, 0x48, 0x3e, 0x17, 0xa8, 0x3a, 0x81, 0xfd, 0x68, 0x31, 0xc4, 0x95, 0x1f, 0x45, 0xe0, 0xde,
	0x5c, 0x82, 0xd2, 0x5f, 0x24, 0xe8, 0x10, 0xda, 0xf7, 0xe5, 0xf5, 0x40, 0x28, 0x6c, 0x15, 0x49,
	0xac, 0x3d, 0x2c, 0x80, 0x52, 0xab, 0x28, 0x4c, 0xe2, 0x39, 0x2b, 0x6b, 0x53, 0x0b, 0xa0, 0x4a,
	0x7b, 0xda, 0x5b, 0x17, 0x6f, 0xdd, 0x9b, 0xe9, 0x12, 0xfe, 0x0b, 0x17, 0x57, 0xdc, 0xda, 0xe5,
	0xcc, 0x21, 0x5b, 0x93, 0x61, 0x3b, 0x3a, 0x4f, 0xef, 0xca, 0x5e, 0x4e, 0xd0, 0xe7, 0xa4, 0xfc,
	0x0a, 0xf4, 0x84, 0x13, 0x28, 0xe9, 0xfe, 0xdc, 0xd8, 0x66, 0x57, 0x6a, 0xe5, 0xde, 0xc2, 0x61,
	0xae, 0xad, 0x9c, 0x9d, 0x7c, 0x3a, 0x1e, 0x08, 0x7d, 0x95, 0xf4, 0x1b, 0x1c, 0x87, 0x4d, 0x38,
	0xe0, 0x28, 0x71, 0x28, 0x78, 0x33, 0xbb, 0xde, 0x9b, 0x8b, 0x3f, 0x1d, 0x8e, 0xa7, 0xa5, 0xfe,
	0x66, 0xa6, 0x7b, 0xfc, 0x33, 0x00, 0x00, 0xff, 0xff, 0x05, 0x4c, 0x9f, 0x87, 0x65, 0x08, 0x00,
	0x00,
}
