// Code generated by protoc-gen-go. DO NOT EDIT.
// source: imageservice/imageservice.proto

package imageservice // import "github.com/e-conomic/ssn-protobuf/imageservice"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ImageFormat int32

const (
	ImageFormat_PNG  ImageFormat = 0
	ImageFormat_JPEG ImageFormat = 1
)

var ImageFormat_name = map[int32]string{
	0: "PNG",
	1: "JPEG",
}

var ImageFormat_value = map[string]int32{
	"PNG":  0,
	"JPEG": 1,
}

func (x ImageFormat) String() string {
	return proto.EnumName(ImageFormat_name, int32(x))
}

func (ImageFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_16257ece80842f2c, []int{0}
}

type Language int32

const (
	Language_ENG Language = 0
	Language_DAN Language = 1
	Language_SWE Language = 2
	Language_NOR Language = 3
	Language_FIN Language = 4
	Language_NLD Language = 5
)

var Language_name = map[int32]string{
	0: "ENG",
	1: "DAN",
	2: "SWE",
	3: "NOR",
	4: "FIN",
	5: "NLD",
}

var Language_value = map[string]int32{
	"ENG": 0,
	"DAN": 1,
	"SWE": 2,
	"NOR": 3,
	"FIN": 4,
	"NLD": 5,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}

func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_16257ece80842f2c, []int{1}
}

type Image struct {
	Data                 []byte      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Format               ImageFormat `protobuf:"varint,2,opt,name=format,proto3,enum=imageservice.ImageFormat" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_16257ece80842f2c, []int{0}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Image) GetFormat() ImageFormat {
	if m != nil {
		return m.Format
	}
	return ImageFormat_PNG
}

type PdfRasterizerRequest struct {
	PdfBytes             []byte   `protobuf:"bytes,1,opt,name=pdfBytes,proto3" json:"pdfBytes,omitempty"`
	Indecies             []uint32 `protobuf:"varint,2,rep,packed,name=indecies,proto3" json:"indecies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PdfRasterizerRequest) Reset()         { *m = PdfRasterizerRequest{} }
func (m *PdfRasterizerRequest) String() string { return proto.CompactTextString(m) }
func (*PdfRasterizerRequest) ProtoMessage()    {}
func (*PdfRasterizerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16257ece80842f2c, []int{1}
}
func (m *PdfRasterizerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PdfRasterizerRequest.Unmarshal(m, b)
}
func (m *PdfRasterizerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PdfRasterizerRequest.Marshal(b, m, deterministic)
}
func (dst *PdfRasterizerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PdfRasterizerRequest.Merge(dst, src)
}
func (m *PdfRasterizerRequest) XXX_Size() int {
	return xxx_messageInfo_PdfRasterizerRequest.Size(m)
}
func (m *PdfRasterizerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PdfRasterizerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PdfRasterizerRequest proto.InternalMessageInfo

func (m *PdfRasterizerRequest) GetPdfBytes() []byte {
	if m != nil {
		return m.PdfBytes
	}
	return nil
}

func (m *PdfRasterizerRequest) GetIndecies() []uint32 {
	if m != nil {
		return m.Indecies
	}
	return nil
}

type PdfRasterizerResponse struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Image                *Image   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PdfRasterizerResponse) Reset()         { *m = PdfRasterizerResponse{} }
func (m *PdfRasterizerResponse) String() string { return proto.CompactTextString(m) }
func (*PdfRasterizerResponse) ProtoMessage()    {}
func (*PdfRasterizerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16257ece80842f2c, []int{2}
}
func (m *PdfRasterizerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PdfRasterizerResponse.Unmarshal(m, b)
}
func (m *PdfRasterizerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PdfRasterizerResponse.Marshal(b, m, deterministic)
}
func (dst *PdfRasterizerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PdfRasterizerResponse.Merge(dst, src)
}
func (m *PdfRasterizerResponse) XXX_Size() int {
	return xxx_messageInfo_PdfRasterizerResponse.Size(m)
}
func (m *PdfRasterizerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PdfRasterizerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PdfRasterizerResponse proto.InternalMessageInfo

func (m *PdfRasterizerResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PdfRasterizerResponse) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type OcrRequest struct {
	Image                *Image   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Lang                 Language `protobuf:"varint,2,opt,name=lang,proto3,enum=imageservice.Language" json:"lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OcrRequest) Reset()         { *m = OcrRequest{} }
func (m *OcrRequest) String() string { return proto.CompactTextString(m) }
func (*OcrRequest) ProtoMessage()    {}
func (*OcrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16257ece80842f2c, []int{3}
}
func (m *OcrRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OcrRequest.Unmarshal(m, b)
}
func (m *OcrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OcrRequest.Marshal(b, m, deterministic)
}
func (dst *OcrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OcrRequest.Merge(dst, src)
}
func (m *OcrRequest) XXX_Size() int {
	return xxx_messageInfo_OcrRequest.Size(m)
}
func (m *OcrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OcrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OcrRequest proto.InternalMessageInfo

func (m *OcrRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *OcrRequest) GetLang() Language {
	if m != nil {
		return m.Lang
	}
	return Language_ENG
}

type OcrResponse struct {
	Hocr                 string   `protobuf:"bytes,1,opt,name=hocr,proto3" json:"hocr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OcrResponse) Reset()         { *m = OcrResponse{} }
func (m *OcrResponse) String() string { return proto.CompactTextString(m) }
func (*OcrResponse) ProtoMessage()    {}
func (*OcrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16257ece80842f2c, []int{4}
}
func (m *OcrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OcrResponse.Unmarshal(m, b)
}
func (m *OcrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OcrResponse.Marshal(b, m, deterministic)
}
func (dst *OcrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OcrResponse.Merge(dst, src)
}
func (m *OcrResponse) XXX_Size() int {
	return xxx_messageInfo_OcrResponse.Size(m)
}
func (m *OcrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OcrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OcrResponse proto.InternalMessageInfo

func (m *OcrResponse) GetHocr() string {
	if m != nil {
		return m.Hocr
	}
	return ""
}

func init() {
	proto.RegisterType((*Image)(nil), "imageservice.Image")
	proto.RegisterType((*PdfRasterizerRequest)(nil), "imageservice.PdfRasterizerRequest")
	proto.RegisterType((*PdfRasterizerResponse)(nil), "imageservice.PdfRasterizerResponse")
	proto.RegisterType((*OcrRequest)(nil), "imageservice.OcrRequest")
	proto.RegisterType((*OcrResponse)(nil), "imageservice.OcrResponse")
	proto.RegisterEnum("imageservice.ImageFormat", ImageFormat_name, ImageFormat_value)
	proto.RegisterEnum("imageservice.Language", Language_name, Language_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImageServiceClient interface {
	GetOcr(ctx context.Context, in *OcrRequest, opts ...grpc.CallOption) (*OcrResponse, error)
	PdfRasterizer(ctx context.Context, in *PdfRasterizerRequest, opts ...grpc.CallOption) (ImageService_PdfRasterizerClient, error)
}

type imageServiceClient struct {
	cc *grpc.ClientConn
}

func NewImageServiceClient(cc *grpc.ClientConn) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) GetOcr(ctx context.Context, in *OcrRequest, opts ...grpc.CallOption) (*OcrResponse, error) {
	out := new(OcrResponse)
	err := c.cc.Invoke(ctx, "/imageservice.ImageService/GetOcr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) PdfRasterizer(ctx context.Context, in *PdfRasterizerRequest, opts ...grpc.CallOption) (ImageService_PdfRasterizerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ImageService_serviceDesc.Streams[0], "/imageservice.ImageService/PdfRasterizer", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageServicePdfRasterizerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ImageService_PdfRasterizerClient interface {
	Recv() (*PdfRasterizerResponse, error)
	grpc.ClientStream
}

type imageServicePdfRasterizerClient struct {
	grpc.ClientStream
}

func (x *imageServicePdfRasterizerClient) Recv() (*PdfRasterizerResponse, error) {
	m := new(PdfRasterizerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServiceServer is the server API for ImageService service.
type ImageServiceServer interface {
	GetOcr(context.Context, *OcrRequest) (*OcrResponse, error)
	PdfRasterizer(*PdfRasterizerRequest, ImageService_PdfRasterizerServer) error
}

func RegisterImageServiceServer(s *grpc.Server, srv ImageServiceServer) {
	s.RegisterService(&_ImageService_serviceDesc, srv)
}

func _ImageService_GetOcr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OcrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).GetOcr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imageservice.ImageService/GetOcr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).GetOcr(ctx, req.(*OcrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_PdfRasterizer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PdfRasterizerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageServiceServer).PdfRasterizer(m, &imageServicePdfRasterizerServer{stream})
}

type ImageService_PdfRasterizerServer interface {
	Send(*PdfRasterizerResponse) error
	grpc.ServerStream
}

type imageServicePdfRasterizerServer struct {
	grpc.ServerStream
}

func (x *imageServicePdfRasterizerServer) Send(m *PdfRasterizerResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imageservice.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOcr",
			Handler:    _ImageService_GetOcr_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PdfRasterizer",
			Handler:       _ImageService_PdfRasterizer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "imageservice/imageservice.proto",
}

func init() { proto.RegisterFile("imageservice/imageservice.proto", fileDescriptor_16257ece80842f2c) }

var fileDescriptor_16257ece80842f2c = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x8e, 0x93, 0x40,
	0x14, 0xdd, 0x29, 0xd0, 0xad, 0xb7, 0xad, 0x21, 0xe3, 0x6a, 0xd8, 0xbe, 0x88, 0xf8, 0x52, 0x9b,
	0x2c, 0x5d, 0xeb, 0x07, 0xa8, 0x9b, 0xed, 0x36, 0x6b, 0x1a, 0xda, 0x4c, 0x1f, 0x34, 0xc6, 0x17,
	0x3a, 0x0c, 0x94, 0x44, 0x98, 0xca, 0x0c, 0x46, 0xfd, 0x27, 0xff, 0xd1, 0xcc, 0x40, 0xb1, 0x98,
	0xc6, 0x7d, 0x3b, 0x67, 0xee, 0xb9, 0xe7, 0x1e, 0x2e, 0x17, 0x9e, 0xa7, 0x59, 0x98, 0x30, 0xc1,
	0x8a, 0xef, 0x29, 0x65, 0xd3, 0x63, 0xe2, 0xef, 0x0b, 0x2e, 0x39, 0x1e, 0x1c, 0xbf, 0x79, 0x01,
	0x58, 0xf7, 0x8a, 0x63, 0x0c, 0x66, 0x14, 0xca, 0xd0, 0x41, 0x2e, 0x1a, 0x0f, 0x88, 0xc6, 0xf8,
	0x35, 0x74, 0x63, 0x5e, 0x64, 0xa1, 0x74, 0x3a, 0x2e, 0x1a, 0x3f, 0x9e, 0x5d, 0xfa, 0x2d, 0x3f,
	0xdd, 0x78, 0xa7, 0x05, 0xa4, 0x16, 0x7a, 0x01, 0x5c, 0xac, 0xa3, 0x98, 0x84, 0x42, 0xb2, 0x22,
	0xfd, 0xc5, 0x0a, 0xc2, 0xbe, 0x95, 0x4c, 0x48, 0x3c, 0x82, 0xde, 0x3e, 0x8a, 0x6f, 0x7e, 0x4a,
	0x26, 0xea, 0x11, 0x0d, 0x57, 0xb5, 0x34, 0x8f, 0x18, 0x4d, 0x99, 0x70, 0x3a, 0xae, 0x31, 0x1e,
	0x92, 0x86, 0x7b, 0x9f, 0xe0, 0xe9, 0x3f, 0x7e, 0x62, 0xcf, 0x73, 0xc1, 0xf0, 0x05, 0x58, 0x4a,
	0xf4, 0x43, 0xbb, 0x0d, 0x49, 0x45, 0xf0, 0x2b, 0xb0, 0x74, 0x44, 0x1d, 0xb8, 0x3f, 0x7b, 0x72,
	0x22, 0x30, 0xa9, 0x14, 0x1e, 0x05, 0x58, 0xd1, 0x26, 0x5f, 0xd3, 0x88, 0x1e, 0x6a, 0xc4, 0x13,
	0x30, 0xbf, 0x86, 0x79, 0x52, 0xef, 0xe4, 0x59, 0x5b, 0xb9, 0x0c, 0xf3, 0xa4, 0x54, 0x62, 0xad,
	0xf1, 0x5e, 0x40, 0x5f, 0x0f, 0xa9, 0x43, 0x63, 0x30, 0x77, 0x9c, 0x16, 0x7a, 0xc8, 0x23, 0xa2,
	0xf1, 0xc4, 0x85, 0xfe, 0xd1, 0x22, 0xf1, 0x39, 0x18, 0xeb, 0x60, 0x61, 0x9f, 0xe1, 0x1e, 0x98,
	0x1f, 0xd6, 0xf3, 0x85, 0x8d, 0x26, 0xef, 0xa0, 0x77, 0xb0, 0x55, 0xe5, 0xb9, 0x2e, 0x9f, 0x83,
	0x71, 0xfb, 0x3e, 0xb0, 0x91, 0x02, 0x9b, 0x8f, 0x73, 0xbb, 0xa3, 0x40, 0xb0, 0x22, 0xb6, 0xa1,
	0xc0, 0xdd, 0x7d, 0x60, 0x9b, 0xfa, 0x65, 0x79, 0x6b, 0x5b, 0xb3, 0xdf, 0x08, 0x06, 0x7a, 0xc8,
	0xa6, 0x8a, 0x89, 0xdf, 0x42, 0x77, 0xc1, 0xe4, 0x8a, 0x16, 0xd8, 0x69, 0xe7, 0xff, 0xbb, 0x92,
	0xd1, 0xe5, 0x89, 0x4a, 0xf5, 0x1d, 0xde, 0x19, 0xfe, 0x02, 0xc3, 0xd6, 0x7f, 0xc1, 0x5e, 0x5b,
	0x7d, 0xea, 0x08, 0x46, 0x2f, 0xff, 0xab, 0x39, 0x78, 0x5f, 0xa3, 0x9b, 0xeb, 0xcf, 0x7e, 0x92,
	0xca, 0x5d, 0xb9, 0xf5, 0x29, 0xcf, 0xa6, 0xec, 0x8a, 0xf2, 0x9c, 0x67, 0x29, 0x9d, 0x0a, 0x91,
	0x5f, 0xe9, 0x2b, 0xde, 0x96, 0x71, 0xeb, 0xb6, 0xb7, 0x5d, 0xfd, 0xfc, 0xe6, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x28, 0xef, 0x22, 0x87, 0xff, 0x02, 0x00, 0x00,
}
