// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssn/scanner/v1/scanner.proto

package scanner // import "github.com/e-conomic/vmlapis/ssn/scanner/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1 "github.com/e-conomic/vmlapis/ssn/mlservice/v1"
import v11 "github.com/e-conomic/vmlapis/ssn/ocrservice/v1"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Feature_Type int32

const (
	Feature_DOCUMENT_FIELD_DETECTION Feature_Type = 0
	Feature_RAW_TEXT_DETECTION       Feature_Type = 1
	// INTERNAL is for internal debugging
	Feature_INTERNAL_OCR_RESPONSES Feature_Type = 100
)

var Feature_Type_name = map[int32]string{
	0:   "DOCUMENT_FIELD_DETECTION",
	1:   "RAW_TEXT_DETECTION",
	100: "INTERNAL_OCR_RESPONSES",
}
var Feature_Type_value = map[string]int32{
	"DOCUMENT_FIELD_DETECTION": 0,
	"RAW_TEXT_DETECTION":       1,
	"INTERNAL_OCR_RESPONSES":   100,
}

func (x Feature_Type) String() string {
	return proto.EnumName(Feature_Type_name, int32(x))
}
func (Feature_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_scanner_3e1f4ddeca6efa24, []int{0, 0}
}

type Feature struct {
	Type                 Feature_Type `protobuf:"varint,1,opt,name=type,proto3,enum=ssn.scanner.v1.Feature_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_scanner_3e1f4ddeca6efa24, []int{0}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetType() Feature_Type {
	if m != nil {
		return m.Type
	}
	return Feature_DOCUMENT_FIELD_DETECTION
}

type ScanRequest struct {
	Image                []byte     `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Features             []*Feature `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_scanner_3e1f4ddeca6efa24, []int{1}
}
func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (dst *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(dst, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ScanRequest) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type ScanResponse struct {
	DocumentFieldDetection *v1.MlResponse              `protobuf:"bytes,1,opt,name=documentFieldDetection,proto3" json:"documentFieldDetection,omitempty"`
	RawTextDetection       string                      `protobuf:"bytes,2,opt,name=rawTextDetection,proto3" json:"rawTextDetection,omitempty"`
	InternalOcrResponses   []*v11.OcrScanImageResponse `protobuf:"bytes,100,rep,name=internalOcrResponses,proto3" json:"internalOcrResponses,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                    `json:"-"`
	XXX_unrecognized       []byte                      `json:"-"`
	XXX_sizecache          int32                       `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_scanner_3e1f4ddeca6efa24, []int{2}
}
func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (dst *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(dst, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetDocumentFieldDetection() *v1.MlResponse {
	if m != nil {
		return m.DocumentFieldDetection
	}
	return nil
}

func (m *ScanResponse) GetRawTextDetection() string {
	if m != nil {
		return m.RawTextDetection
	}
	return ""
}

func (m *ScanResponse) GetInternalOcrResponses() []*v11.OcrScanImageResponse {
	if m != nil {
		return m.InternalOcrResponses
	}
	return nil
}

func init() {
	proto.RegisterType((*Feature)(nil), "ssn.scanner.v1.Feature")
	proto.RegisterType((*ScanRequest)(nil), "ssn.scanner.v1.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "ssn.scanner.v1.ScanResponse")
	proto.RegisterEnum("ssn.scanner.v1.Feature_Type", Feature_Type_name, Feature_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScannerClient is the client API for Scanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScannerClient interface {
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type scannerClient struct {
	cc *grpc.ClientConn
}

func NewScannerClient(cc *grpc.ClientConn) ScannerClient {
	return &scannerClient{cc}
}

func (c *scannerClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/ssn.scanner.v1.Scanner/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerServer is the server API for Scanner service.
type ScannerServer interface {
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
}

func RegisterScannerServer(s *grpc.Server, srv ScannerServer) {
	s.RegisterService(&_Scanner_serviceDesc, srv)
}

func _Scanner_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssn.scanner.v1.Scanner/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssn.scanner.v1.Scanner",
	HandlerType: (*ScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scan",
			Handler:    _Scanner_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssn/scanner/v1/scanner.proto",
}

func init() {
	proto.RegisterFile("ssn/scanner/v1/scanner.proto", fileDescriptor_scanner_3e1f4ddeca6efa24)
}

var fileDescriptor_scanner_3e1f4ddeca6efa24 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0xa5, 0xb0, 0xe1, 0x8e, 0xa9, 0x32, 0x53, 0xa9, 0x4a, 0x1e, 0xaa, 0xbc, 0x50, 0x4d,
	0x22, 0xa1, 0xad, 0x78, 0x81, 0xa7, 0xd1, 0xa6, 0x52, 0xa5, 0x2d, 0x41, 0x4e, 0x80, 0x0a, 0x1e,
	0x22, 0xcf, 0xbd, 0x94, 0x48, 0x89, 0x1d, 0x6c, 0x37, 0xb0, 0x57, 0x7e, 0x01, 0xf1, 0x65, 0xfc,
	0x02, 0xaf, 0xfc, 0x03, 0x4a, 0xd2, 0xb4, 0x1d, 0x6c, 0x6f, 0xf7, 0x5e, 0x9f, 0x73, 0x7c, 0x7c,
	0x7c, 0x91, 0xa9, 0x14, 0x77, 0x14, 0xa3, 0x9c, 0x83, 0x74, 0xf2, 0x61, 0x5d, 0xda, 0x99, 0x14,
	0x5a, 0xe0, 0x63, 0xa5, 0xb8, 0x5d, 0x8f, 0xf2, 0x61, 0xcf, 0x2a, 0xd0, 0x82, 0x49, 0x05, 0x32,
	0x8f, 0x19, 0x14, 0x84, 0x5d, 0x57, 0x71, 0x7a, 0xfd, 0x02, 0x93, 0x26, 0x7b, 0x90, 0x6d, 0xb3,
	0x41, 0x98, 0x2b, 0x21, 0x56, 0x09, 0x38, 0x34, 0x8b, 0x1d, 0xca, 0xb9, 0xd0, 0x54, 0xc7, 0x82,
	0xab, 0xea, 0xd4, 0xfa, 0x69, 0xa0, 0x83, 0x19, 0x50, 0xbd, 0x96, 0x80, 0x9f, 0xa3, 0xa6, 0xbe,
	0xca, 0xa0, 0x6b, 0xf4, 0x8d, 0xc1, 0xf1, 0xc8, 0xb4, 0xaf, 0xdb, 0xb1, 0x37, 0x30, 0x3b, 0xbc,
	0xca, 0x80, 0x94, 0x48, 0x6b, 0x81, 0x9a, 0x45, 0x87, 0x4d, 0xd4, 0x9d, 0xfa, 0x93, 0xb7, 0x17,
	0xae, 0x17, 0x46, 0xb3, 0xb9, 0x7b, 0x3e, 0x8d, 0xa6, 0x6e, 0xe8, 0x4e, 0xc2, 0xb9, 0xef, 0xb5,
	0xef, 0xe0, 0x0e, 0xc2, 0xe4, 0xec, 0x7d, 0x14, 0xba, 0x8b, 0x70, 0x6f, 0x6e, 0xe0, 0x1e, 0xea,
	0xcc, 0xbd, 0xd0, 0x25, 0xde, 0xd9, 0x79, 0xe4, 0x4f, 0x48, 0x44, 0xdc, 0xe0, 0x8d, 0xef, 0x05,
	0x6e, 0xd0, 0x5e, 0x5a, 0x0b, 0xd4, 0x0a, 0x18, 0xe5, 0x04, 0xbe, 0xac, 0x41, 0x69, 0x7c, 0x82,
	0xee, 0xc5, 0x29, 0x5d, 0x55, 0xde, 0x8e, 0x48, 0xd5, 0xe0, 0x31, 0x3a, 0xfc, 0x54, 0x99, 0x52,
	0xdd, 0x46, 0xff, 0xee, 0xa0, 0x35, 0x7a, 0x7c, 0x8b, 0x69, 0xb2, 0x05, 0x5a, 0x7f, 0x0c, 0x74,
	0x54, 0x49, 0xab, 0x4c, 0x70, 0x05, 0x38, 0x44, 0x9d, 0xa5, 0x60, 0xeb, 0x14, 0xb8, 0x9e, 0xc5,
	0x90, 0x2c, 0xa7, 0xa0, 0x81, 0x15, 0x19, 0x95, 0x97, 0xb5, 0x36, 0x41, 0xec, 0x62, 0xcd, 0x87,
	0xf6, 0x45, 0x52, 0xb3, 0xc9, 0x2d, 0x5c, 0x7c, 0x8a, 0xda, 0x92, 0x7e, 0x0d, 0xe1, 0x9b, 0xde,
	0xe9, 0x35, 0xfa, 0xc6, 0xe0, 0x01, 0xf9, 0x6f, 0x8e, 0x3f, 0xa2, 0x93, 0x98, 0x6b, 0x90, 0x9c,
	0x26, 0x3e, 0x93, 0xb5, 0xb4, 0xea, 0x2e, 0xcb, 0x37, 0x3d, 0x2d, 0xef, 0xdf, 0xfb, 0xf9, 0x7c,
	0x68, 0xfb, 0x4c, 0x16, 0x6f, 0x98, 0x17, 0x31, 0x6c, 0xad, 0xdc, 0x28, 0x32, 0xa2, 0xe8, 0x20,
	0xa8, 0xf2, 0xc0, 0xef, 0x50, 0xb3, 0x28, 0xf1, 0x93, 0x7f, 0x53, 0xda, 0x8b, 0xba, 0x67, 0xde,
	0x7c, 0x58, 0xc9, 0x59, 0x8f, 0xbe, 0xff, 0xfa, 0xfd, 0xa3, 0xf1, 0xd0, 0x3a, 0xac, 0xd7, 0xf7,
	0xa5, 0x71, 0xfa, 0xfa, 0xc5, 0x87, 0xf1, 0x2a, 0xd6, 0x9f, 0xd7, 0x97, 0x36, 0x13, 0xa9, 0x03,
	0xcf, 0x98, 0xe0, 0x22, 0x8d, 0x99, 0x93, 0xa7, 0x09, 0xcd, 0x62, 0xe5, 0x5c, 0xdf, 0xfa, 0x57,
	0x9b, 0xf2, 0xf2, 0x7e, 0xb9, 0x82, 0xe3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x83, 0x27,
	0x7c, 0x16, 0x03, 0x00, 0x00,
}
