//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ssn/scanner/v1alpha1/scanner.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

public protocol Scanner_ScannerInternalScanCall: ClientCallUnary {}

fileprivate final class Scanner_ScannerInternalScanCallBase: ClientCallUnaryBase<Scanner_InternalScanRequest, Scanner_InternalScanResponse>, Scanner_ScannerInternalScanCall {
  override class var method: String { return "/scanner.Scanner/InternalScan" }
}

public protocol Scanner_ScannerScanCall: ClientCallUnary {}

fileprivate final class Scanner_ScannerScanCallBase: ClientCallUnaryBase<Scanner_ScanRequest, Scanner_ScanResponse>, Scanner_ScannerScanCall {
  override class var method: String { return "/scanner.Scanner/Scan" }
}


/// Instantiate Scanner_ScannerServiceClient, then call methods of this protocol to make API calls.
public protocol Scanner_ScannerService: ServiceClient {
  /// Synchronous. Unary.
  func internalScan(_ request: Scanner_InternalScanRequest) throws -> Scanner_InternalScanResponse
  /// Asynchronous. Unary.
  func internalScan(_ request: Scanner_InternalScanRequest, completion: @escaping (Scanner_InternalScanResponse?, CallResult) -> Void) throws -> Scanner_ScannerInternalScanCall

  /// Synchronous. Unary.
  func scan(_ request: Scanner_ScanRequest) throws -> Scanner_ScanResponse
  /// Asynchronous. Unary.
  func scan(_ request: Scanner_ScanRequest, completion: @escaping (Scanner_ScanResponse?, CallResult) -> Void) throws -> Scanner_ScannerScanCall

}

public final class Scanner_ScannerServiceClient: ServiceClientBase, Scanner_ScannerService {
  /// Synchronous. Unary.
  public func internalScan(_ request: Scanner_InternalScanRequest) throws -> Scanner_InternalScanResponse {
    return try Scanner_ScannerInternalScanCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  public func internalScan(_ request: Scanner_InternalScanRequest, completion: @escaping (Scanner_InternalScanResponse?, CallResult) -> Void) throws -> Scanner_ScannerInternalScanCall {
    return try Scanner_ScannerInternalScanCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  public func scan(_ request: Scanner_ScanRequest) throws -> Scanner_ScanResponse {
    return try Scanner_ScannerScanCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  public func scan(_ request: Scanner_ScanRequest, completion: @escaping (Scanner_ScanResponse?, CallResult) -> Void) throws -> Scanner_ScannerScanCall {
    return try Scanner_ScannerScanCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

