// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssn/scanner/v1alpha1/scanner.proto

package scanner // import "github.com/e-conomic/proto/ssn/scanner/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1alpha11 "github.com/e-conomic/proto/ssn/mlservice/v1alpha1"
import v1alpha1 "github.com/e-conomic/proto/ssn/ocrservice/v1alpha1"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Feature_Type int32

const (
	Feature_DOCUMENT_FIELD_DETECTION Feature_Type = 0
	Feature_RAW_TEXT_DETECTION       Feature_Type = 1
)

var Feature_Type_name = map[int32]string{
	0: "DOCUMENT_FIELD_DETECTION",
	1: "RAW_TEXT_DETECTION",
}
var Feature_Type_value = map[string]int32{
	"DOCUMENT_FIELD_DETECTION": 0,
	"RAW_TEXT_DETECTION":       1,
}

func (x Feature_Type) String() string {
	return proto.EnumName(Feature_Type_name, int32(x))
}
func (Feature_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_scanner_b3a73a34b2c26218, []int{2, 0}
}

type InternalScanRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalScanRequest) Reset()         { *m = InternalScanRequest{} }
func (m *InternalScanRequest) String() string { return proto.CompactTextString(m) }
func (*InternalScanRequest) ProtoMessage()    {}
func (*InternalScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_scanner_b3a73a34b2c26218, []int{0}
}
func (m *InternalScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalScanRequest.Unmarshal(m, b)
}
func (m *InternalScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalScanRequest.Marshal(b, m, deterministic)
}
func (dst *InternalScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalScanRequest.Merge(dst, src)
}
func (m *InternalScanRequest) XXX_Size() int {
	return xxx_messageInfo_InternalScanRequest.Size(m)
}
func (m *InternalScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalScanRequest proto.InternalMessageInfo

func (m *InternalScanRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type InternalScanResponse struct {
	Ocr                  []*v1alpha1.OcrScanImageResponse `protobuf:"bytes,1,rep,name=ocr,proto3" json:"ocr,omitempty"`
	Ml                   *v1alpha11.MlResponse            `protobuf:"bytes,2,opt,name=ml,proto3" json:"ml,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *InternalScanResponse) Reset()         { *m = InternalScanResponse{} }
func (m *InternalScanResponse) String() string { return proto.CompactTextString(m) }
func (*InternalScanResponse) ProtoMessage()    {}
func (*InternalScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_scanner_b3a73a34b2c26218, []int{1}
}
func (m *InternalScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalScanResponse.Unmarshal(m, b)
}
func (m *InternalScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalScanResponse.Marshal(b, m, deterministic)
}
func (dst *InternalScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalScanResponse.Merge(dst, src)
}
func (m *InternalScanResponse) XXX_Size() int {
	return xxx_messageInfo_InternalScanResponse.Size(m)
}
func (m *InternalScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalScanResponse proto.InternalMessageInfo

func (m *InternalScanResponse) GetOcr() []*v1alpha1.OcrScanImageResponse {
	if m != nil {
		return m.Ocr
	}
	return nil
}

func (m *InternalScanResponse) GetMl() *v1alpha11.MlResponse {
	if m != nil {
		return m.Ml
	}
	return nil
}

type Feature struct {
	Type                 Feature_Type `protobuf:"varint,1,opt,name=type,proto3,enum=scanner.Feature_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_scanner_b3a73a34b2c26218, []int{2}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetType() Feature_Type {
	if m != nil {
		return m.Type
	}
	return Feature_DOCUMENT_FIELD_DETECTION
}

type ScanRequest struct {
	Image                []byte     `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Features             []*Feature `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_scanner_b3a73a34b2c26218, []int{3}
}
func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (dst *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(dst, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ScanRequest) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type ScanResponse struct {
	DocumentFieldDetection *v1alpha11.MlResponse `protobuf:"bytes,1,opt,name=documentFieldDetection,proto3" json:"documentFieldDetection,omitempty"`
	RawTextDetection       string                `protobuf:"bytes,2,opt,name=rawTextDetection,proto3" json:"rawTextDetection,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_scanner_b3a73a34b2c26218, []int{4}
}
func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (dst *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(dst, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetDocumentFieldDetection() *v1alpha11.MlResponse {
	if m != nil {
		return m.DocumentFieldDetection
	}
	return nil
}

func (m *ScanResponse) GetRawTextDetection() string {
	if m != nil {
		return m.RawTextDetection
	}
	return ""
}

func init() {
	proto.RegisterType((*InternalScanRequest)(nil), "scanner.InternalScanRequest")
	proto.RegisterType((*InternalScanResponse)(nil), "scanner.InternalScanResponse")
	proto.RegisterType((*Feature)(nil), "scanner.Feature")
	proto.RegisterType((*ScanRequest)(nil), "scanner.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "scanner.ScanResponse")
	proto.RegisterEnum("scanner.Feature_Type", Feature_Type_name, Feature_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScannerClient is the client API for Scanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScannerClient interface {
	InternalScan(ctx context.Context, in *InternalScanRequest, opts ...grpc.CallOption) (*InternalScanResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type scannerClient struct {
	cc *grpc.ClientConn
}

func NewScannerClient(cc *grpc.ClientConn) ScannerClient {
	return &scannerClient{cc}
}

func (c *scannerClient) InternalScan(ctx context.Context, in *InternalScanRequest, opts ...grpc.CallOption) (*InternalScanResponse, error) {
	out := new(InternalScanResponse)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/InternalScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/scanner.Scanner/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerServer is the server API for Scanner service.
type ScannerServer interface {
	InternalScan(context.Context, *InternalScanRequest) (*InternalScanResponse, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
}

func RegisterScannerServer(s *grpc.Server, srv ScannerServer) {
	s.RegisterService(&_Scanner_serviceDesc, srv)
}

func _Scanner_InternalScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).InternalScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/InternalScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).InternalScan(ctx, req.(*InternalScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scanner_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.Scanner/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scanner.Scanner",
	HandlerType: (*ScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalScan",
			Handler:    _Scanner_InternalScan_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _Scanner_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssn/scanner/v1alpha1/scanner.proto",
}

func init() {
	proto.RegisterFile("ssn/scanner/v1alpha1/scanner.proto", fileDescriptor_scanner_b3a73a34b2c26218)
}

var fileDescriptor_scanner_b3a73a34b2c26218 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0x6b, 0x37, 0x50, 0xb8, 0x89, 0xaa, 0x68, 0x9a, 0x54, 0x26, 0x0a, 0x52, 0x64, 0x09,
	0x94, 0x56, 0x60, 0xab, 0x66, 0x81, 0xf8, 0xd9, 0x40, 0xe3, 0x48, 0x91, 0x48, 0x22, 0x5c, 0x23,
	0x10, 0x9b, 0x68, 0x3a, 0xb9, 0xa4, 0x96, 0xec, 0x19, 0x77, 0x3c, 0x29, 0x74, 0xcb, 0x8e, 0x35,
	0x2f, 0xc1, 0xfb, 0xf0, 0x0a, 0x3c, 0x08, 0xf2, 0x4f, 0x1c, 0xa7, 0x6d, 0x76, 0xbe, 0xe7, 0x7e,
	0xd7, 0x73, 0xe6, 0xcc, 0x0c, 0x98, 0x49, 0xc2, 0xed, 0x84, 0x51, 0xce, 0x51, 0xda, 0x57, 0x27,
	0x34, 0x8c, 0x2f, 0xe8, 0xc9, 0x4a, 0xb0, 0x62, 0x29, 0x94, 0x20, 0x7b, 0x45, 0xd9, 0xe9, 0xa7,
	0xb0, 0x60, 0x32, 0x41, 0x79, 0x15, 0x30, 0x5c, 0xf3, 0x6b, 0x2d, 0x1f, 0xe9, 0x3c, 0x4d, 0xc9,
	0x28, 0xbc, 0x05, 0x96, 0x52, 0xc1, 0x75, 0x17, 0x42, 0x2c, 0x42, 0xb4, 0x69, 0x1c, 0xd8, 0x94,
	0x73, 0xa1, 0xa8, 0x0a, 0x04, 0x4f, 0xf2, 0xae, 0x79, 0x04, 0x07, 0x23, 0xae, 0x50, 0x72, 0x1a,
	0x9e, 0x31, 0xca, 0x3d, 0xbc, 0x5c, 0x62, 0xa2, 0x08, 0x81, 0xda, 0x9c, 0x2a, 0x6a, 0x68, 0x3d,
	0xad, 0xdf, 0xf0, 0xb2, 0x6f, 0xf3, 0x12, 0x5a, 0x9b, 0x68, 0x12, 0x0b, 0x9e, 0x20, 0x71, 0x60,
	0x57, 0x30, 0x69, 0x68, 0xbd, 0xdd, 0x7e, 0xdd, 0xe9, 0x59, 0x15, 0xa3, 0x53, 0x26, 0x53, 0x72,
	0x14, 0xd1, 0x05, 0xae, 0x70, 0x2f, 0x85, 0xc9, 0x13, 0xd0, 0xa3, 0xd0, 0xd0, 0x7b, 0x5a, 0xbf,
	0xee, 0xb4, 0xad, 0xb5, 0xe5, 0x71, 0x58, 0x72, 0x7a, 0x14, 0x9a, 0x12, 0xf6, 0x86, 0x48, 0xd5,
	0x52, 0x22, 0x39, 0x82, 0x9a, 0xba, 0x8e, 0x31, 0x73, 0xb4, 0xef, 0xb4, 0xad, 0x55, 0x7e, 0x45,
	0xdf, 0xf2, 0xaf, 0x63, 0xf4, 0x32, 0xc4, 0x7c, 0x0b, 0xb5, 0xb4, 0x22, 0x5d, 0x30, 0x06, 0xd3,
	0xd3, 0x4f, 0x63, 0x77, 0xe2, 0xcf, 0x86, 0x23, 0xf7, 0xc3, 0x60, 0x36, 0x70, 0x7d, 0xf7, 0xd4,
	0x1f, 0x4d, 0x27, 0xcd, 0x1d, 0x72, 0x08, 0xc4, 0x7b, 0xf7, 0x79, 0xe6, 0xbb, 0x5f, 0xfc, 0x8a,
	0xae, 0x99, 0x1f, 0xa1, 0x5e, 0x4d, 0xa2, 0x05, 0xf7, 0x82, 0xd4, 0x7f, 0x11, 0x45, 0x5e, 0x90,
	0x67, 0xf0, 0xe0, 0x5b, 0xbe, 0x70, 0x62, 0xe8, 0xd9, 0xc6, 0x9b, 0x37, 0x1d, 0x79, 0x25, 0x61,
	0xfe, 0xd2, 0xa0, 0xb1, 0x11, 0xd9, 0x18, 0x0e, 0xe7, 0x82, 0x2d, 0x23, 0xe4, 0x6a, 0x18, 0x60,
	0x38, 0x1f, 0xa0, 0x42, 0x96, 0x1e, 0x4b, 0xb6, 0xca, 0xd6, 0x48, 0xb6, 0x0c, 0x91, 0x63, 0x68,
	0x4a, 0xfa, 0xdd, 0xc7, 0x1f, 0x6a, 0xfd, 0xa3, 0x34, 0xdb, 0x87, 0xde, 0x2d, 0xdd, 0xf9, 0xa3,
	0xc1, 0xde, 0x59, 0xee, 0x94, 0x8c, 0xa1, 0x51, 0x3d, 0x51, 0xd2, 0x2d, 0xf7, 0x70, 0xc7, 0x9d,
	0xe8, 0x3c, 0xde, 0xd2, 0xcd, 0xcd, 0x99, 0x3b, 0x64, 0x02, 0xb5, 0xec, 0x37, 0xad, 0x12, 0xac,
	0x8e, 0xb7, 0x6f, 0xa8, 0xc5, 0xd8, 0xa3, 0x9f, 0x7f, 0xff, 0xfd, 0xd6, 0x0f, 0xcc, 0xfd, 0xcd,
	0xa7, 0xf1, 0x5a, 0x3b, 0x7e, 0xff, 0xea, 0xeb, 0xcb, 0x45, 0xa0, 0x2e, 0x96, 0xe7, 0x16, 0x13,
	0x91, 0x8d, 0xcf, 0x99, 0xe0, 0x22, 0x0a, 0x98, 0x9d, 0xdd, 0x5c, 0xfb, 0xae, 0x57, 0xf5, 0xa6,
	0x10, 0xce, 0xef, 0x67, 0xcc, 0x8b, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0x6b, 0x7d, 0x85,
	0x7c, 0x03, 0x00, 0x00,
}
