// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ovlservice/ovlservice.proto

package ssn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PredictedField struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Confidence           uint32   `protobuf:"varint,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictedField) Reset()         { *m = PredictedField{} }
func (m *PredictedField) String() string { return proto.CompactTextString(m) }
func (*PredictedField) ProtoMessage()    {}
func (*PredictedField) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a8dc8250c63b52e, []int{0}
}
func (m *PredictedField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictedField.Unmarshal(m, b)
}
func (m *PredictedField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictedField.Marshal(b, m, deterministic)
}
func (dst *PredictedField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictedField.Merge(dst, src)
}
func (m *PredictedField) XXX_Size() int {
	return xxx_messageInfo_PredictedField.Size(m)
}
func (m *PredictedField) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictedField.DiscardUnknown(m)
}

var xxx_messageInfo_PredictedField proto.InternalMessageInfo

func (m *PredictedField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PredictedField) GetConfidence() uint32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type OvlRequest struct {
	Ocr                  string   `protobuf:"bytes,1,opt,name=ocr,proto3" json:"ocr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OvlRequest) Reset()         { *m = OvlRequest{} }
func (m *OvlRequest) String() string { return proto.CompactTextString(m) }
func (*OvlRequest) ProtoMessage()    {}
func (*OvlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a8dc8250c63b52e, []int{1}
}
func (m *OvlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OvlRequest.Unmarshal(m, b)
}
func (m *OvlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OvlRequest.Marshal(b, m, deterministic)
}
func (dst *OvlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OvlRequest.Merge(dst, src)
}
func (m *OvlRequest) XXX_Size() int {
	return xxx_messageInfo_OvlRequest.Size(m)
}
func (m *OvlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OvlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OvlRequest proto.InternalMessageInfo

func (m *OvlRequest) GetOcr() string {
	if m != nil {
		return m.Ocr
	}
	return ""
}

type OvlResponse struct {
	TotalIncludingVat    *PredictedField `protobuf:"bytes,1,opt,name=totalIncludingVat,proto3" json:"totalIncludingVat,omitempty"`
	VatDistributionSE12  *PredictedField `protobuf:"bytes,2,opt,name=vatDistributionSE12,proto3" json:"vatDistributionSE12,omitempty"`
	VatDistributionSE25  *PredictedField `protobuf:"bytes,3,opt,name=vatDistributionSE25,proto3" json:"vatDistributionSE25,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OvlResponse) Reset()         { *m = OvlResponse{} }
func (m *OvlResponse) String() string { return proto.CompactTextString(m) }
func (*OvlResponse) ProtoMessage()    {}
func (*OvlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a8dc8250c63b52e, []int{2}
}
func (m *OvlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OvlResponse.Unmarshal(m, b)
}
func (m *OvlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OvlResponse.Marshal(b, m, deterministic)
}
func (dst *OvlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OvlResponse.Merge(dst, src)
}
func (m *OvlResponse) XXX_Size() int {
	return xxx_messageInfo_OvlResponse.Size(m)
}
func (m *OvlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OvlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OvlResponse proto.InternalMessageInfo

func (m *OvlResponse) GetTotalIncludingVat() *PredictedField {
	if m != nil {
		return m.TotalIncludingVat
	}
	return nil
}

func (m *OvlResponse) GetVatDistributionSE12() *PredictedField {
	if m != nil {
		return m.VatDistributionSE12
	}
	return nil
}

func (m *OvlResponse) GetVatDistributionSE25() *PredictedField {
	if m != nil {
		return m.VatDistributionSE25
	}
	return nil
}

func init() {
	proto.RegisterType((*PredictedField)(nil), "ssn.PredictedField")
	proto.RegisterType((*OvlRequest)(nil), "ssn.OvlRequest")
	proto.RegisterType((*OvlResponse)(nil), "ssn.OvlResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OvlServiceClient is the client API for OvlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OvlServiceClient interface {
	GetPrediction(ctx context.Context, in *OvlRequest, opts ...grpc.CallOption) (*OvlResponse, error)
}

type ovlServiceClient struct {
	cc *grpc.ClientConn
}

func NewOvlServiceClient(cc *grpc.ClientConn) OvlServiceClient {
	return &ovlServiceClient{cc}
}

func (c *ovlServiceClient) GetPrediction(ctx context.Context, in *OvlRequest, opts ...grpc.CallOption) (*OvlResponse, error) {
	out := new(OvlResponse)
	err := c.cc.Invoke(ctx, "/ssn.OvlService/GetPrediction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OvlServiceServer is the server API for OvlService service.
type OvlServiceServer interface {
	GetPrediction(context.Context, *OvlRequest) (*OvlResponse, error)
}

func RegisterOvlServiceServer(s *grpc.Server, srv OvlServiceServer) {
	s.RegisterService(&_OvlService_serviceDesc, srv)
}

func _OvlService_GetPrediction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OvlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OvlServiceServer).GetPrediction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssn.OvlService/GetPrediction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OvlServiceServer).GetPrediction(ctx, req.(*OvlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OvlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssn.OvlService",
	HandlerType: (*OvlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrediction",
			Handler:    _OvlService_GetPrediction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ovlservice/ovlservice.proto",
}

func init() { proto.RegisterFile("ovlservice/ovlservice.proto", fileDescriptor_2a8dc8250c63b52e) }

var fileDescriptor_2a8dc8250c63b52e = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x5d, 0x17, 0x05, 0xa7, 0x54, 0x6b, 0xea, 0x61, 0x51, 0x28, 0x65, 0x4f, 0x3d, 0xad,
	0x18, 0xed, 0x03, 0x28, 0xb6, 0xe2, 0x49, 0xd9, 0x82, 0xf7, 0x6d, 0x32, 0x4a, 0x20, 0x24, 0x35,
	0x33, 0x9b, 0xc7, 0xf5, 0x59, 0xc4, 0x6c, 0x61, 0x15, 0xeb, 0xc1, 0xdb, 0x64, 0xf8, 0xf3, 0xf1,
	0xf3, 0x0d, 0x5c, 0xf8, 0x68, 0x09, 0x43, 0x34, 0x0a, 0x2f, 0xfb, 0xb1, 0xda, 0x04, 0xcf, 0x5e,
	0xe4, 0x44, 0xae, 0x5c, 0xc2, 0xf1, 0x73, 0x40, 0x6d, 0x14, 0xa3, 0x5e, 0x1a, 0xb4, 0x5a, 0x9c,
	0xc1, 0x41, 0x6c, 0x6c, 0x8b, 0x45, 0x36, 0xcd, 0x66, 0x47, 0x75, 0xf7, 0x10, 0x13, 0x00, 0xe5,
	0xdd, 0xab, 0xd1, 0xe8, 0x14, 0x16, 0xfb, 0xd3, 0x6c, 0x36, 0xac, 0xbf, 0x6d, 0xca, 0x09, 0xc0,
	0x53, 0xb4, 0x35, 0xbe, 0xb7, 0x48, 0x2c, 0x46, 0x90, 0x7b, 0x15, 0xb6, 0x84, 0xaf, 0xb1, 0xfc,
	0xc8, 0x60, 0x90, 0x02, 0xb4, 0xf1, 0x8e, 0x50, 0xdc, 0xc2, 0x29, 0x7b, 0x6e, 0xec, 0xa3, 0x53,
	0xb6, 0xd5, 0xc6, 0xbd, 0xbd, 0x34, 0x9c, 0xf2, 0x03, 0x39, 0xae, 0x88, 0x5c, 0xf5, 0xb3, 0x55,
	0xfd, 0x3b, 0x2d, 0x16, 0x30, 0x8e, 0x0d, 0xdf, 0x1b, 0xe2, 0x60, 0xd6, 0x2d, 0x1b, 0xef, 0x56,
	0x8b, 0x2b, 0x99, 0xba, 0xfd, 0x01, 0xd9, 0x95, 0xdf, 0x89, 0x91, 0xf3, 0x22, 0xff, 0x0f, 0x46,
	0xce, 0xe5, 0x5d, 0x12, 0xb0, 0xea, 0x0c, 0x8b, 0x1b, 0x18, 0x3e, 0x20, 0x6f, 0xff, 0x19, 0xef,
	0xc4, 0x49, 0x02, 0xf5, 0x8a, 0xce, 0x47, 0xfd, 0xa2, 0x53, 0x52, 0xee, 0xad, 0x0f, 0xd3, 0x61,
	0xae, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x21, 0x4a, 0xaf, 0xb7, 0x01, 0x00, 0x00,
}
