// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssn/mlservice/v1/mlservice.proto

package mlservicev1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
	v1 "ssn/ocrservice/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PredictedField struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Confidence           float32  `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictedField) Reset()         { *m = PredictedField{} }
func (m *PredictedField) String() string { return proto.CompactTextString(m) }
func (*PredictedField) ProtoMessage()    {}
func (*PredictedField) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a943bb12778a93, []int{0}
}

func (m *PredictedField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictedField.Unmarshal(m, b)
}
func (m *PredictedField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictedField.Marshal(b, m, deterministic)
}
func (m *PredictedField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictedField.Merge(m, src)
}
func (m *PredictedField) XXX_Size() int {
	return xxx_messageInfo_PredictedField.Size(m)
}
func (m *PredictedField) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictedField.DiscardUnknown(m)
}

var xxx_messageInfo_PredictedField proto.InternalMessageInfo

func (m *PredictedField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PredictedField) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type MlRequest struct {
	OcrResponses         []*v1.OcrScanImageResponse `protobuf:"bytes,1,rep,name=ocrResponses,proto3" json:"ocrResponses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *MlRequest) Reset()         { *m = MlRequest{} }
func (m *MlRequest) String() string { return proto.CompactTextString(m) }
func (*MlRequest) ProtoMessage()    {}
func (*MlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a943bb12778a93, []int{1}
}

func (m *MlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlRequest.Unmarshal(m, b)
}
func (m *MlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlRequest.Marshal(b, m, deterministic)
}
func (m *MlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlRequest.Merge(m, src)
}
func (m *MlRequest) XXX_Size() int {
	return xxx_messageInfo_MlRequest.Size(m)
}
func (m *MlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MlRequest proto.InternalMessageInfo

func (m *MlRequest) GetOcrResponses() []*v1.OcrScanImageResponse {
	if m != nil {
		return m.OcrResponses
	}
	return nil
}

type MlResponse struct {
	// orderDate
	// ISO 8601 date string, ie. a string of the format "YYYY-MM-DD"
	// Example: "2019-12-31"
	OrderDate *PredictedField `protobuf:"bytes,1,opt,name=orderDate,proto3" json:"orderDate,omitempty"`
	// paymentDueDate
	// ISO 8601 date, ie. a string of the format "YYYY-MM-DD"
	// Example: "2019-12-31"
	PaymentDueDate *PredictedField `protobuf:"bytes,2,opt,name=paymentDueDate,proto3" json:"paymentDueDate,omitempty"`
	// currency
	// ISO 4217 string, ie. a 3-letter capitalized string
	// Example: "NOK"
	Currency *PredictedField `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	// totalVat
	// A string that parses as a two-decimal number
	// Example: "10.0" or "11.11"
	TotalVat *PredictedField `protobuf:"bytes,4,opt,name=totalVat,proto3" json:"totalVat,omitempty"`
	// totalInclVat
	// A string that parses as a two-decimal number
	// Example: "10.0" or "11.11"
	TotalInclVat *PredictedField `protobuf:"bytes,5,opt,name=totalInclVat,proto3" json:"totalInclVat,omitempty"`
	// totalExclVat
	// A string that parses as a two-decimal number
	// Example: "10.0" or "11.11"
	TotalExclVat *PredictedField `protobuf:"bytes,6,opt,name=totalExclVat,proto3" json:"totalExclVat,omitempty"`
	// supplierCorporateId
	// The company VAT number
	// Example: "123456789B01" (for Dutch companies)
	// or "12345678" (for Norwegian companies)
	// Note: The field is repeated because multiple VAT numbers might exist.
	// If you have the VAT number of you customer, you can use this information
	// to find out which VAT number belongs to the supplier of the invoice.
	SupplierCorporateId []*PredictedField `protobuf:"bytes,7,rep,name=supplierCorporateId,proto3" json:"supplierCorporateId,omitempty"`
	// supplierCountryCode
	// ISO 3166-1 alpha-2 string, ei. a two-letter capitalized string
	// Example: "NO"
	SupplierCountryCode *PredictedField `protobuf:"bytes,8,opt,name=supplierCountryCode,proto3" json:"supplierCountryCode,omitempty"`
	// documentType
	// Either "Receipt" or "Invoice"
	DocumentType *PredictedField `protobuf:"bytes,9,opt,name=documentType,proto3" json:"documentType,omitempty"`
	// paymentMethod
	// Either "Cash" or "CreditCard"
	PaymentMethod *PredictedField `protobuf:"bytes,10,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	// creditCardLastFourDigits
	// Four digits
	// Example: "0012"
	CreditCardLastFourDigits *PredictedField `protobuf:"bytes,11,opt,name=creditCardLastFourDigits,proto3" json:"creditCardLastFourDigits,omitempty"`
	// invoiceNumber
	// The supplier defined identifier af the invoice
	// Example: "12345-A99"
	InvoiceNumber *PredictedField `protobuf:"bytes,17,opt,name=invoiceNumber,proto3" json:"invoiceNumber,omitempty"`
	// Only one ocrLine will be present in a suggestion.
	//
	// Types that are valid to be assigned to OcrLine:
	//	*MlResponse_OcrLineDk_
	//	*MlResponse_OcrLineSe_
	//	*MlResponse_OcrLineNo_
	//	*MlResponse_OcrLineFi_
	//	*MlResponse_OcrLineNl_
	OcrLine              isMlResponse_OcrLine `protobuf_oneof:"ocrLine"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MlResponse) Reset()         { *m = MlResponse{} }
func (m *MlResponse) String() string { return proto.CompactTextString(m) }
func (*MlResponse) ProtoMessage()    {}
func (*MlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a943bb12778a93, []int{2}
}

func (m *MlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse.Unmarshal(m, b)
}
func (m *MlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse.Marshal(b, m, deterministic)
}
func (m *MlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse.Merge(m, src)
}
func (m *MlResponse) XXX_Size() int {
	return xxx_messageInfo_MlResponse.Size(m)
}
func (m *MlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse proto.InternalMessageInfo

func (m *MlResponse) GetOrderDate() *PredictedField {
	if m != nil {
		return m.OrderDate
	}
	return nil
}

func (m *MlResponse) GetPaymentDueDate() *PredictedField {
	if m != nil {
		return m.PaymentDueDate
	}
	return nil
}

func (m *MlResponse) GetCurrency() *PredictedField {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *MlResponse) GetTotalVat() *PredictedField {
	if m != nil {
		return m.TotalVat
	}
	return nil
}

func (m *MlResponse) GetTotalInclVat() *PredictedField {
	if m != nil {
		return m.TotalInclVat
	}
	return nil
}

func (m *MlResponse) GetTotalExclVat() *PredictedField {
	if m != nil {
		return m.TotalExclVat
	}
	return nil
}

func (m *MlResponse) GetSupplierCorporateId() []*PredictedField {
	if m != nil {
		return m.SupplierCorporateId
	}
	return nil
}

func (m *MlResponse) GetSupplierCountryCode() *PredictedField {
	if m != nil {
		return m.SupplierCountryCode
	}
	return nil
}

func (m *MlResponse) GetDocumentType() *PredictedField {
	if m != nil {
		return m.DocumentType
	}
	return nil
}

func (m *MlResponse) GetPaymentMethod() *PredictedField {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

func (m *MlResponse) GetCreditCardLastFourDigits() *PredictedField {
	if m != nil {
		return m.CreditCardLastFourDigits
	}
	return nil
}

func (m *MlResponse) GetInvoiceNumber() *PredictedField {
	if m != nil {
		return m.InvoiceNumber
	}
	return nil
}

type isMlResponse_OcrLine interface {
	isMlResponse_OcrLine()
}

type MlResponse_OcrLineDk_ struct {
	OcrLineDk *MlResponse_OcrLineDk `protobuf:"bytes,12,opt,name=ocrLineDk,proto3,oneof"`
}

type MlResponse_OcrLineSe_ struct {
	OcrLineSe *MlResponse_OcrLineSe `protobuf:"bytes,13,opt,name=ocrLineSe,proto3,oneof"`
}

type MlResponse_OcrLineNo_ struct {
	OcrLineNo *MlResponse_OcrLineNo `protobuf:"bytes,14,opt,name=ocrLineNo,proto3,oneof"`
}

type MlResponse_OcrLineFi_ struct {
	OcrLineFi *MlResponse_OcrLineFi `protobuf:"bytes,15,opt,name=ocrLineFi,proto3,oneof"`
}

type MlResponse_OcrLineNl_ struct {
	OcrLineNl *MlResponse_OcrLineNl `protobuf:"bytes,16,opt,name=ocrLineNl,proto3,oneof"`
}

func (*MlResponse_OcrLineDk_) isMlResponse_OcrLine() {}

func (*MlResponse_OcrLineSe_) isMlResponse_OcrLine() {}

func (*MlResponse_OcrLineNo_) isMlResponse_OcrLine() {}

func (*MlResponse_OcrLineFi_) isMlResponse_OcrLine() {}

func (*MlResponse_OcrLineNl_) isMlResponse_OcrLine() {}

func (m *MlResponse) GetOcrLine() isMlResponse_OcrLine {
	if m != nil {
		return m.OcrLine
	}
	return nil
}

func (m *MlResponse) GetOcrLineDk() *MlResponse_OcrLineDk {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineDk_); ok {
		return x.OcrLineDk
	}
	return nil
}

func (m *MlResponse) GetOcrLineSe() *MlResponse_OcrLineSe {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineSe_); ok {
		return x.OcrLineSe
	}
	return nil
}

func (m *MlResponse) GetOcrLineNo() *MlResponse_OcrLineNo {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineNo_); ok {
		return x.OcrLineNo
	}
	return nil
}

func (m *MlResponse) GetOcrLineFi() *MlResponse_OcrLineFi {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineFi_); ok {
		return x.OcrLineFi
	}
	return nil
}

func (m *MlResponse) GetOcrLineNl() *MlResponse_OcrLineNl {
	if x, ok := m.GetOcrLine().(*MlResponse_OcrLineNl_); ok {
		return x.OcrLineNl
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MlResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MlResponse_OcrLineDk_)(nil),
		(*MlResponse_OcrLineSe_)(nil),
		(*MlResponse_OcrLineNo_)(nil),
		(*MlResponse_OcrLineFi_)(nil),
		(*MlResponse_OcrLineNl_)(nil),
	}
}

type MlResponse_OcrLineDk struct {
	// example: "71"
	Type *PredictedField `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// example: "000002879094031"
	PaymentId *PredictedField `protobuf:"bytes,2,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	//example: "86570807"
	CreditorId           *PredictedField `protobuf:"bytes,3,opt,name=creditorId,proto3" json:"creditorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineDk) Reset()         { *m = MlResponse_OcrLineDk{} }
func (m *MlResponse_OcrLineDk) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineDk) ProtoMessage()    {}
func (*MlResponse_OcrLineDk) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a943bb12778a93, []int{2, 0}
}

func (m *MlResponse_OcrLineDk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineDk.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineDk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineDk.Marshal(b, m, deterministic)
}
func (m *MlResponse_OcrLineDk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineDk.Merge(m, src)
}
func (m *MlResponse_OcrLineDk) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineDk.Size(m)
}
func (m *MlResponse_OcrLineDk) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineDk.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineDk proto.InternalMessageInfo

func (m *MlResponse_OcrLineDk) GetType() *PredictedField {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *MlResponse_OcrLineDk) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func (m *MlResponse_OcrLineDk) GetCreditorId() *PredictedField {
	if m != nil {
		return m.CreditorId
	}
	return nil
}

type MlResponse_OcrLineSe struct {
	// example: "050765098"
	PaymentId *PredictedField `protobuf:"bytes,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	// example: "2654507"
	BankgiroCreditorId *PredictedField `protobuf:"bytes,2,opt,name=bankgiroCreditorId,proto3" json:"bankgiroCreditorId,omitempty"`
	// example: "5000872"
	PlusgiroCreditorId   *PredictedField `protobuf:"bytes,3,opt,name=plusgiroCreditorId,proto3" json:"plusgiroCreditorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineSe) Reset()         { *m = MlResponse_OcrLineSe{} }
func (m *MlResponse_OcrLineSe) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineSe) ProtoMessage()    {}
func (*MlResponse_OcrLineSe) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a943bb12778a93, []int{2, 1}
}

func (m *MlResponse_OcrLineSe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineSe.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineSe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineSe.Marshal(b, m, deterministic)
}
func (m *MlResponse_OcrLineSe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineSe.Merge(m, src)
}
func (m *MlResponse_OcrLineSe) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineSe.Size(m)
}
func (m *MlResponse_OcrLineSe) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineSe.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineSe proto.InternalMessageInfo

func (m *MlResponse_OcrLineSe) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func (m *MlResponse_OcrLineSe) GetBankgiroCreditorId() *PredictedField {
	if m != nil {
		return m.BankgiroCreditorId
	}
	return nil
}

func (m *MlResponse_OcrLineSe) GetPlusgiroCreditorId() *PredictedField {
	if m != nil {
		return m.PlusgiroCreditorId
	}
	return nil
}

type MlResponse_OcrLineNo struct {
	// example: "12345678903"
	PaymentId            *PredictedField `protobuf:"bytes,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineNo) Reset()         { *m = MlResponse_OcrLineNo{} }
func (m *MlResponse_OcrLineNo) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineNo) ProtoMessage()    {}
func (*MlResponse_OcrLineNo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a943bb12778a93, []int{2, 2}
}

func (m *MlResponse_OcrLineNo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineNo.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineNo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineNo.Marshal(b, m, deterministic)
}
func (m *MlResponse_OcrLineNo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineNo.Merge(m, src)
}
func (m *MlResponse_OcrLineNo) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineNo.Size(m)
}
func (m *MlResponse_OcrLineNo) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineNo.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineNo proto.InternalMessageInfo

func (m *MlResponse_OcrLineNo) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

type MlResponse_OcrLineNl struct {
	// example: "0817937867870002"
	PaymentId            *PredictedField `protobuf:"bytes,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineNl) Reset()         { *m = MlResponse_OcrLineNl{} }
func (m *MlResponse_OcrLineNl) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineNl) ProtoMessage()    {}
func (*MlResponse_OcrLineNl) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a943bb12778a93, []int{2, 3}
}

func (m *MlResponse_OcrLineNl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineNl.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineNl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineNl.Marshal(b, m, deterministic)
}
func (m *MlResponse_OcrLineNl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineNl.Merge(m, src)
}
func (m *MlResponse_OcrLineNl) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineNl.Size(m)
}
func (m *MlResponse_OcrLineNl) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineNl.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineNl proto.InternalMessageInfo

func (m *MlResponse_OcrLineNl) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

type MlResponse_OcrLineFi struct {
	// example: "00000159220010146012"
	PaymentId            *PredictedField `protobuf:"bytes,1,opt,name=paymentId,proto3" json:"paymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MlResponse_OcrLineFi) Reset()         { *m = MlResponse_OcrLineFi{} }
func (m *MlResponse_OcrLineFi) String() string { return proto.CompactTextString(m) }
func (*MlResponse_OcrLineFi) ProtoMessage()    {}
func (*MlResponse_OcrLineFi) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a943bb12778a93, []int{2, 4}
}

func (m *MlResponse_OcrLineFi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MlResponse_OcrLineFi.Unmarshal(m, b)
}
func (m *MlResponse_OcrLineFi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MlResponse_OcrLineFi.Marshal(b, m, deterministic)
}
func (m *MlResponse_OcrLineFi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MlResponse_OcrLineFi.Merge(m, src)
}
func (m *MlResponse_OcrLineFi) XXX_Size() int {
	return xxx_messageInfo_MlResponse_OcrLineFi.Size(m)
}
func (m *MlResponse_OcrLineFi) XXX_DiscardUnknown() {
	xxx_messageInfo_MlResponse_OcrLineFi.DiscardUnknown(m)
}

var xxx_messageInfo_MlResponse_OcrLineFi proto.InternalMessageInfo

func (m *MlResponse_OcrLineFi) GetPaymentId() *PredictedField {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func init() {
	proto.RegisterType((*PredictedField)(nil), "ssn.mlservice.v1.PredictedField")
	proto.RegisterType((*MlRequest)(nil), "ssn.mlservice.v1.MlRequest")
	proto.RegisterType((*MlResponse)(nil), "ssn.mlservice.v1.MlResponse")
	proto.RegisterType((*MlResponse_OcrLineDk)(nil), "ssn.mlservice.v1.MlResponse.OcrLineDk")
	proto.RegisterType((*MlResponse_OcrLineSe)(nil), "ssn.mlservice.v1.MlResponse.OcrLineSe")
	proto.RegisterType((*MlResponse_OcrLineNo)(nil), "ssn.mlservice.v1.MlResponse.OcrLineNo")
	proto.RegisterType((*MlResponse_OcrLineNl)(nil), "ssn.mlservice.v1.MlResponse.OcrLineNl")
	proto.RegisterType((*MlResponse_OcrLineFi)(nil), "ssn.mlservice.v1.MlResponse.OcrLineFi")
}

func init() { proto.RegisterFile("ssn/mlservice/v1/mlservice.proto", fileDescriptor_c1a943bb12778a93) }

var fileDescriptor_c1a943bb12778a93 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdf, 0x6e, 0xd3, 0x3c,
	0x18, 0xc6, 0xd7, 0xfd, 0xcf, 0xdb, 0x75, 0xdb, 0xe7, 0x8f, 0x03, 0xab, 0x20, 0x54, 0xf5, 0x00,
	0x76, 0xd4, 0xa9, 0x83, 0x43, 0x84, 0xd0, 0x5a, 0xc2, 0xaa, 0x6d, 0x65, 0x4a, 0x11, 0x02, 0xc4,
	0x49, 0xe6, 0xbc, 0x0c, 0x6b, 0xa9, 0x1d, 0x1c, 0x27, 0xa2, 0xf7, 0xc0, 0x5d, 0x71, 0x41, 0xdc,
	0x02, 0x72, 0xd2, 0x35, 0x6e, 0x29, 0xe0, 0x69, 0x9c, 0xd5, 0xa9, 0x7f, 0x3f, 0x3d, 0x4f, 0xf3,
	0xc6, 0x0d, 0xb4, 0xd2, 0x54, 0x1c, 0x8e, 0xe3, 0x14, 0x55, 0xce, 0x19, 0x1e, 0xe6, 0xdd, 0x6a,
	0xd1, 0x49, 0x94, 0xd4, 0x92, 0xec, 0xa7, 0xa9, 0xe8, 0x54, 0x17, 0xf3, 0x6e, 0xb3, 0x6d, 0x18,
	0xc9, 0x94, 0x05, 0x55, 0xab, 0x92, 0x6a, 0xfb, 0xb0, 0x7b, 0xa1, 0x30, 0xe2, 0x4c, 0x63, 0xe4,
	0x73, 0x8c, 0x23, 0x72, 0x0f, 0x36, 0xf2, 0x30, 0xce, 0x90, 0xd6, 0x5a, 0xb5, 0x03, 0x2f, 0x28,
	0x17, 0xe4, 0x21, 0x00, 0x93, 0xe2, 0x13, 0x8f, 0x50, 0x30, 0xa4, 0xab, 0xad, 0xda, 0xc1, 0x6a,
	0x60, 0x5d, 0x69, 0xbf, 0x03, 0xef, 0x3c, 0x0e, 0xf0, 0x4b, 0x86, 0xa9, 0x26, 0xa7, 0xb0, 0x23,
	0x99, 0x0a, 0x30, 0x4d, 0xa4, 0x48, 0x31, 0xa5, 0xb5, 0xd6, 0xda, 0x41, 0xfd, 0xe8, 0x71, 0xc7,
	0x24, 0xb4, 0x12, 0xe4, 0xdd, 0xce, 0x6b, 0xa6, 0x46, 0x2c, 0x14, 0x83, 0x71, 0x78, 0x85, 0x37,
	0xfb, 0x83, 0x39, 0xb8, 0xfd, 0x6d, 0x0f, 0xc0, 0xa8, 0xcb, 0x35, 0x79, 0x0e, 0x9e, 0x54, 0x11,
	0xaa, 0x7e, 0xa8, 0xcb, 0x88, 0xf5, 0xa3, 0x56, 0x67, 0xb1, 0x7a, 0x67, 0xbe, 0x53, 0x50, 0x21,
	0xe4, 0x04, 0x76, 0x93, 0x70, 0x32, 0x46, 0xa1, 0xfb, 0x19, 0x16, 0x92, 0x55, 0x47, 0xc9, 0x02,
	0x47, 0x9e, 0xc1, 0x36, 0xcb, 0x94, 0x42, 0xc1, 0x26, 0x74, 0xcd, 0xd1, 0x31, 0x23, 0x0c, 0xad,
	0xa5, 0x0e, 0xe3, 0xb7, 0xa1, 0xa6, 0xeb, 0xae, 0xf4, 0x0d, 0x41, 0xfa, 0xb0, 0x53, 0x7c, 0x1e,
	0x08, 0x56, 0x18, 0x36, 0x1c, 0x0d, 0x73, 0xd4, 0xcc, 0xf2, 0xf2, 0x6b, 0x69, 0xd9, 0xbc, 0x95,
	0x65, 0x4a, 0x91, 0x00, 0xfe, 0x4f, 0xb3, 0x24, 0x89, 0x39, 0xaa, 0x9e, 0x54, 0x89, 0x54, 0xa1,
	0xc6, 0x41, 0x44, 0xb7, 0x8a, 0x9b, 0xfe, 0x77, 0xd9, 0x32, 0x78, 0xde, 0x99, 0x09, 0xad, 0x26,
	0x3d, 0x19, 0x21, 0xdd, 0x76, 0x0c, 0xb8, 0x0c, 0x36, 0x6d, 0x23, 0xc9, 0x32, 0x73, 0x0b, 0xdf,
	0x4c, 0x12, 0xa4, 0x9e, 0x6b, 0x5b, 0x9b, 0x22, 0x3e, 0x34, 0xa6, 0x73, 0x70, 0x8e, 0xfa, 0xb3,
	0x8c, 0x28, 0x38, 0x6a, 0xe6, 0x31, 0xf2, 0x11, 0x28, 0x33, 0x1b, 0x74, 0x2f, 0x54, 0xd1, 0x59,
	0x98, 0x6a, 0x5f, 0x66, 0xaa, 0xcf, 0xaf, 0xb8, 0x4e, 0x69, 0xdd, 0x51, 0xf9, 0x5b, 0x83, 0x49,
	0xc9, 0x45, 0x2e, 0x39, 0xc3, 0x61, 0x36, 0xbe, 0x44, 0x45, 0xff, 0x73, 0x4d, 0x39, 0x87, 0x11,
	0x1f, 0x3c, 0xc9, 0xd4, 0x19, 0x17, 0xd8, 0xbf, 0xa6, 0x3b, 0x85, 0xe3, 0xd1, 0xaf, 0x8e, 0xea,
	0xf1, 0x34, 0x0f, 0x74, 0xb9, 0xfb, 0x64, 0x25, 0xa8, 0x50, 0xcb, 0x33, 0x42, 0xda, 0x70, 0xf7,
	0x8c, 0xd0, 0xf2, 0x8c, 0xd0, 0xf2, 0x0c, 0x25, 0xdd, 0x75, 0xf7, 0x0c, 0xa5, 0xe5, 0x19, 0x4a,
	0xcb, 0xe3, 0x73, 0xba, 0xe7, 0xee, 0xf1, 0xb9, 0xe5, 0xf1, 0xb9, 0x9d, 0x27, 0xa6, 0xfb, 0xb7,
	0xc8, 0x13, 0xdb, 0x79, 0xe2, 0xe6, 0xf7, 0x1a, 0x78, 0xb3, 0x9f, 0x8e, 0x3c, 0x85, 0x75, 0x6d,
	0x26, 0xd4, 0xf5, 0x78, 0x2b, 0x76, 0x9b, 0x93, 0x71, 0x3a, 0x62, 0x83, 0xc8, 0xf9, 0x50, 0xab,
	0x10, 0xf2, 0x02, 0xa0, 0x9c, 0x27, 0xa9, 0x06, 0x91, 0xf3, 0x89, 0x66, 0x31, 0xcd, 0x1f, 0x55,
	0x8b, 0xd1, 0x42, 0x9e, 0xda, 0xed, 0xf3, 0x5c, 0x00, 0xb9, 0x0c, 0xc5, 0xf5, 0x15, 0x57, 0xb2,
	0x57, 0xe5, 0x72, 0x2d, 0xb6, 0x84, 0x35, 0xc6, 0x24, 0xce, 0xd2, 0x05, 0xa3, 0x6b, 0xd3, 0x25,
	0x6c, 0xf3, 0x74, 0x56, 0x78, 0x28, 0xef, 0x5a, 0xd8, 0x96, 0xc5, 0xff, 0x50, 0xe6, 0xf3, 0xbb,
	0xca, 0x8e, 0x3d, 0xd8, 0x9a, 0xce, 0xea, 0xd1, 0x7b, 0xf3, 0x47, 0x3f, 0x2a, 0x21, 0x72, 0x06,
	0x8d, 0x57, 0xa8, 0xa7, 0x1c, 0x97, 0x82, 0xdc, 0x5f, 0x3e, 0xfc, 0xc5, 0x6b, 0x41, 0xf3, 0xc1,
	0x9f, 0x9e, 0x8c, 0xf6, 0xca, 0x71, 0xe3, 0x43, 0x7d, 0xf6, 0x65, 0xde, 0xbd, 0xdc, 0x2c, 0xde,
	0x50, 0x9e, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x4c, 0x81, 0x7c, 0xfb, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MlServiceClient is the client API for MlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MlServiceClient interface {
	GetPrediction(ctx context.Context, in *MlRequest, opts ...grpc.CallOption) (*MlResponse, error)
}

type mlServiceClient struct {
	cc *grpc.ClientConn
}

func NewMlServiceClient(cc *grpc.ClientConn) MlServiceClient {
	return &mlServiceClient{cc}
}

func (c *mlServiceClient) GetPrediction(ctx context.Context, in *MlRequest, opts ...grpc.CallOption) (*MlResponse, error) {
	out := new(MlResponse)
	err := c.cc.Invoke(ctx, "/ssn.mlservice.v1.MlService/GetPrediction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlServiceServer is the server API for MlService service.
type MlServiceServer interface {
	GetPrediction(context.Context, *MlRequest) (*MlResponse, error)
}

func RegisterMlServiceServer(s *grpc.Server, srv MlServiceServer) {
	s.RegisterService(&_MlService_serviceDesc, srv)
}

func _MlService_GetPrediction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlServiceServer).GetPrediction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssn.mlservice.v1.MlService/GetPrediction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlServiceServer).GetPrediction(ctx, req.(*MlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssn.mlservice.v1.MlService",
	HandlerType: (*MlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrediction",
			Handler:    _MlService_GetPrediction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssn/mlservice/v1/mlservice.proto",
}
