// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssn/pdfservice/v1/pdfservice.proto

package pdfservicev1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RasterizePdfRequest_Format int32

const (
	RasterizePdfRequest_PNG RasterizePdfRequest_Format = 0
)

var RasterizePdfRequest_Format_name = map[int32]string{
	0: "PNG",
}

var RasterizePdfRequest_Format_value = map[string]int32{
	"PNG": 0,
}

func (x RasterizePdfRequest_Format) String() string {
	return proto.EnumName(RasterizePdfRequest_Format_name, int32(x))
}

func (RasterizePdfRequest_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4660659c7fb84e3b, []int{0, 0}
}

type RasterizePdfRequest struct {
	Data                 []byte                     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Dpi                  uint32                     `protobuf:"varint,2,opt,name=dpi,proto3" json:"dpi,omitempty"`
	Format               RasterizePdfRequest_Format `protobuf:"varint,3,opt,name=format,proto3,enum=ssn.pdfservice.v1.RasterizePdfRequest_Format" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RasterizePdfRequest) Reset()         { *m = RasterizePdfRequest{} }
func (m *RasterizePdfRequest) String() string { return proto.CompactTextString(m) }
func (*RasterizePdfRequest) ProtoMessage()    {}
func (*RasterizePdfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4660659c7fb84e3b, []int{0}
}

func (m *RasterizePdfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RasterizePdfRequest.Unmarshal(m, b)
}
func (m *RasterizePdfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RasterizePdfRequest.Marshal(b, m, deterministic)
}
func (m *RasterizePdfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RasterizePdfRequest.Merge(m, src)
}
func (m *RasterizePdfRequest) XXX_Size() int {
	return xxx_messageInfo_RasterizePdfRequest.Size(m)
}
func (m *RasterizePdfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RasterizePdfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RasterizePdfRequest proto.InternalMessageInfo

func (m *RasterizePdfRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RasterizePdfRequest) GetDpi() uint32 {
	if m != nil {
		return m.Dpi
	}
	return 0
}

func (m *RasterizePdfRequest) GetFormat() RasterizePdfRequest_Format {
	if m != nil {
		return m.Format
	}
	return RasterizePdfRequest_PNG
}

type RasterizePdfResponse struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RasterizePdfResponse) Reset()         { *m = RasterizePdfResponse{} }
func (m *RasterizePdfResponse) String() string { return proto.CompactTextString(m) }
func (*RasterizePdfResponse) ProtoMessage()    {}
func (*RasterizePdfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4660659c7fb84e3b, []int{1}
}

func (m *RasterizePdfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RasterizePdfResponse.Unmarshal(m, b)
}
func (m *RasterizePdfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RasterizePdfResponse.Marshal(b, m, deterministic)
}
func (m *RasterizePdfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RasterizePdfResponse.Merge(m, src)
}
func (m *RasterizePdfResponse) XXX_Size() int {
	return xxx_messageInfo_RasterizePdfResponse.Size(m)
}
func (m *RasterizePdfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RasterizePdfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RasterizePdfResponse proto.InternalMessageInfo

func (m *RasterizePdfResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RasterizePdfResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("ssn.pdfservice.v1.RasterizePdfRequest_Format", RasterizePdfRequest_Format_name, RasterizePdfRequest_Format_value)
	proto.RegisterType((*RasterizePdfRequest)(nil), "ssn.pdfservice.v1.RasterizePdfRequest")
	proto.RegisterType((*RasterizePdfResponse)(nil), "ssn.pdfservice.v1.RasterizePdfResponse")
}

func init() { proto.RegisterFile("ssn/pdfservice/v1/pdfservice.proto", fileDescriptor_4660659c7fb84e3b) }

var fileDescriptor_4660659c7fb84e3b = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x2e, 0xce, 0xd3,
	0x2f, 0x48, 0x49, 0x2b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2f, 0x33, 0x44, 0xe2, 0xe9,
	0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x09, 0x16, 0x17, 0xe7, 0xe9, 0x21, 0x89, 0x96, 0x19, 0x2a,
	0x4d, 0x65, 0xe4, 0x12, 0x0e, 0x4a, 0x2c, 0x2e, 0x49, 0x2d, 0xca, 0xac, 0x4a, 0x0d, 0x48, 0x49,
	0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98, 0x53, 0x0a, 0x32, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0x40, 0x4c, 0x21, 0x57, 0x2e, 0xb6, 0xb4, 0xfc, 0xa2, 0xdc,
	0xc4, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x5d, 0x3d, 0x0c, 0x1b, 0xf4, 0xb0, 0x98,
	0xae, 0xe7, 0x06, 0xd6, 0x14, 0x04, 0xd5, 0xac, 0x24, 0xc8, 0xc5, 0x06, 0x11, 0x11, 0x62, 0xe7,
	0x62, 0x0e, 0xf0, 0x73, 0x17, 0x60, 0x50, 0x72, 0xe0, 0x12, 0x41, 0xd5, 0x58, 0x5c, 0x90, 0x9f,
	0x57, 0x9c, 0x2a, 0x24, 0xc2, 0xc5, 0x9a, 0x99, 0x97, 0x92, 0x5a, 0x01, 0x76, 0x18, 0x6f, 0x10,
	0x84, 0x03, 0x77, 0x2d, 0x13, 0xc2, 0xb5, 0x46, 0x85, 0x5c, 0x5c, 0x01, 0x29, 0x69, 0xc1, 0x10,
	0x87, 0x08, 0x25, 0x73, 0xf1, 0x20, 0x9b, 0x27, 0xa4, 0x46, 0x9c, 0x4b, 0xa5, 0xd4, 0x09, 0xaa,
	0x83, 0x38, 0x4c, 0x89, 0xc1, 0x80, 0xd1, 0x89, 0x2f, 0x8a, 0x07, 0xa1, 0xb2, 0xcc, 0x30, 0x89,
	0x0d, 0x1c, 0xec, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x2c, 0xc6, 0xd8, 0x9c, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PdfServiceClient is the client API for PdfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PdfServiceClient interface {
	RasterizePdf(ctx context.Context, in *RasterizePdfRequest, opts ...grpc.CallOption) (PdfService_RasterizePdfClient, error)
}

type pdfServiceClient struct {
	cc *grpc.ClientConn
}

func NewPdfServiceClient(cc *grpc.ClientConn) PdfServiceClient {
	return &pdfServiceClient{cc}
}

func (c *pdfServiceClient) RasterizePdf(ctx context.Context, in *RasterizePdfRequest, opts ...grpc.CallOption) (PdfService_RasterizePdfClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PdfService_serviceDesc.Streams[0], "/ssn.pdfservice.v1.PdfService/RasterizePdf", opts...)
	if err != nil {
		return nil, err
	}
	x := &pdfServiceRasterizePdfClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PdfService_RasterizePdfClient interface {
	Recv() (*RasterizePdfResponse, error)
	grpc.ClientStream
}

type pdfServiceRasterizePdfClient struct {
	grpc.ClientStream
}

func (x *pdfServiceRasterizePdfClient) Recv() (*RasterizePdfResponse, error) {
	m := new(RasterizePdfResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PdfServiceServer is the server API for PdfService service.
type PdfServiceServer interface {
	RasterizePdf(*RasterizePdfRequest, PdfService_RasterizePdfServer) error
}

func RegisterPdfServiceServer(s *grpc.Server, srv PdfServiceServer) {
	s.RegisterService(&_PdfService_serviceDesc, srv)
}

func _PdfService_RasterizePdf_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RasterizePdfRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PdfServiceServer).RasterizePdf(m, &pdfServiceRasterizePdfServer{stream})
}

type PdfService_RasterizePdfServer interface {
	Send(*RasterizePdfResponse) error
	grpc.ServerStream
}

type pdfServiceRasterizePdfServer struct {
	grpc.ServerStream
}

func (x *pdfServiceRasterizePdfServer) Send(m *RasterizePdfResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PdfService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssn.pdfservice.v1.PdfService",
	HandlerType: (*PdfServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RasterizePdf",
			Handler:       _PdfService_RasterizePdf_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ssn/pdfservice/v1/pdfservice.proto",
}
