// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssn/usermgnt/v1alpha1/usermgnt.proto

package usermgnt // import "github.com/e-conomic/proto/ssn/usermgnt/v1alpha1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	ConsumerId           int64    `protobuf:"varint,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgnt_91ad1fd740a29bd4, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetConsumerId() int64 {
	if m != nil {
		return m.ConsumerId
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Consumer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Tokens               []*Token `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consumer) Reset()         { *m = Consumer{} }
func (m *Consumer) String() string { return proto.CompactTextString(m) }
func (*Consumer) ProtoMessage()    {}
func (*Consumer) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgnt_91ad1fd740a29bd4, []int{1}
}
func (m *Consumer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consumer.Unmarshal(m, b)
}
func (m *Consumer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consumer.Marshal(b, m, deterministic)
}
func (dst *Consumer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consumer.Merge(dst, src)
}
func (m *Consumer) XXX_Size() int {
	return xxx_messageInfo_Consumer.Size(m)
}
func (m *Consumer) XXX_DiscardUnknown() {
	xxx_messageInfo_Consumer.DiscardUnknown(m)
}

var xxx_messageInfo_Consumer proto.InternalMessageInfo

func (m *Consumer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Consumer) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Consumer) GetTokens() []*Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type Token struct {
	ConsumerId           int64                `protobuf:"varint,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	Token                string               `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Active               bool                 `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgnt_91ad1fd740a29bd4, []int{2}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetConsumerId() int64 {
	if m != nil {
		return m.ConsumerId
	}
	return 0
}

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Token) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgnt_91ad1fd740a29bd4, []int{3}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgnt_91ad1fd740a29bd4, []int{4}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "usermgnt.User")
	proto.RegisterType((*Consumer)(nil), "usermgnt.Consumer")
	proto.RegisterType((*Token)(nil), "usermgnt.Token")
	proto.RegisterType((*CreateUserRequest)(nil), "usermgnt.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "usermgnt.CreateUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserMgntClient is the client API for UserMgnt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserMgntClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type userMgntClient struct {
	cc *grpc.ClientConn
}

func NewUserMgntClient(cc *grpc.ClientConn) UserMgntClient {
	return &userMgntClient{cc}
}

func (c *userMgntClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/usermgnt.UserMgnt/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserMgntServer is the server API for UserMgnt service.
type UserMgntServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

func RegisterUserMgntServer(s *grpc.Server, srv UserMgntServer) {
	s.RegisterService(&_UserMgnt_serviceDesc, srv)
}

func _UserMgnt_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMgntServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermgnt.UserMgnt/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMgntServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserMgnt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usermgnt.UserMgnt",
	HandlerType: (*UserMgntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserMgnt_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssn/usermgnt/v1alpha1/usermgnt.proto",
}

func init() {
	proto.RegisterFile("ssn/usermgnt/v1alpha1/usermgnt.proto", fileDescriptor_usermgnt_91ad1fd740a29bd4)
}

var fileDescriptor_usermgnt_91ad1fd740a29bd4 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0x6b, 0xfa, 0x40,
	0x10, 0x25, 0x89, 0x91, 0x38, 0x82, 0x3f, 0x7e, 0x4b, 0x29, 0xc1, 0x16, 0x0c, 0x41, 0x68, 0x2e,
	0x4d, 0xd0, 0x1e, 0x8a, 0x48, 0x0f, 0xad, 0x87, 0xd2, 0x43, 0x2f, 0xa9, 0xbd, 0xf4, 0x22, 0x31,
	0x99, 0xc6, 0xa5, 0x66, 0x37, 0xcd, 0x6e, 0xfc, 0x1e, 0xfd, 0xc6, 0x25, 0x9b, 0x44, 0x05, 0x3d,
	0xf4, 0xf8, 0xfe, 0xcc, 0xee, 0x9b, 0xc7, 0xc0, 0x58, 0x08, 0x16, 0x94, 0x02, 0x8b, 0x2c, 0x65,
	0x32, 0xd8, 0x4d, 0xa2, 0x6d, 0xbe, 0x89, 0x26, 0x7b, 0xc6, 0xcf, 0x0b, 0x2e, 0x39, 0xb1, 0x5a,
	0x3c, 0x1c, 0xa5, 0x9c, 0xa7, 0x5b, 0x0c, 0x14, 0xbf, 0x2e, 0x3f, 0x03, 0x49, 0x33, 0x14, 0x32,
	0xca, 0xf2, 0xda, 0xea, 0x3e, 0x40, 0xe7, 0x5d, 0x60, 0x41, 0x46, 0xd0, 0x8f, 0x39, 0x13, 0x65,
	0x86, 0xc5, 0x8a, 0x26, 0xb6, 0xe6, 0x68, 0x9e, 0x11, 0x42, 0x4b, 0xbd, 0x24, 0xe4, 0x02, 0x4c,
	0xcc, 0x22, 0xba, 0xb5, 0x75, 0x47, 0xf3, 0x7a, 0x61, 0x0d, 0x5c, 0x0a, 0xd6, 0xa2, 0xf1, 0x90,
	0x01, 0xe8, 0xfb, 0x49, 0x9d, 0x26, 0x64, 0x0c, 0x66, 0x95, 0x43, 0xd8, 0xba, 0x63, 0x78, 0xfd,
	0xe9, 0xc0, 0xdf, 0xa7, 0xac, 0x7e, 0x0c, 0x6b, 0x91, 0xdc, 0x40, 0x57, 0xf2, 0x2f, 0x64, 0xc2,
	0x36, 0x94, 0xed, 0xdf, 0xc1, 0xb6, 0xac, 0xf8, 0xb0, 0x91, 0xdd, 0x1f, 0x0d, 0x4c, 0xc5, 0xfc,
	0x29, 0xab, 0x1a, 0x6a, 0xb3, 0x2a, 0x40, 0x2e, 0xa1, 0x1b, 0xc5, 0x92, 0xee, 0xd0, 0x36, 0x1c,
	0xcd, 0xb3, 0xc2, 0x06, 0x91, 0x19, 0x40, 0x5c, 0x60, 0x24, 0x31, 0x59, 0x45, 0xd2, 0xee, 0x38,
	0x9a, 0xd7, 0x9f, 0x0e, 0xfd, 0xba, 0x38, 0xbf, 0x2d, 0xce, 0x5f, 0xb6, 0xc5, 0x85, 0xbd, 0xc6,
	0xfd, 0x28, 0xdd, 0x7b, 0xf8, 0xbf, 0x50, 0x40, 0x6d, 0x84, 0xdf, 0x25, 0x0a, 0x49, 0x5c, 0xe8,
	0x54, 0x2b, 0xa8, 0x5c, 0xa7, 0x6b, 0x2b, 0xcd, 0x1d, 0x03, 0x39, 0x1e, 0x14, 0x39, 0x67, 0x02,
	0x8f, 0x1a, 0x34, 0xab, 0x06, 0xa7, 0x6f, 0x60, 0x55, 0xfa, 0x6b, 0xca, 0x24, 0x79, 0x06, 0x38,
	0x4c, 0x90, 0xab, 0xc3, 0xab, 0x27, 0x01, 0x86, 0xd7, 0xe7, 0xc5, 0xfa, 0x93, 0xa7, 0xf9, 0xc7,
	0x2c, 0xa5, 0x72, 0x53, 0xae, 0xfd, 0x98, 0x67, 0x01, 0xde, 0xc6, 0x9c, 0xf1, 0x8c, 0xc6, 0xf5,
	0x89, 0x04, 0x67, 0xef, 0x6b, 0xde, 0x32, 0xeb, 0xae, 0x72, 0xdd, 0xfd, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x53, 0x5a, 0xbf, 0xea, 0x88, 0x02, 0x00, 0x00,
}
