// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssn/apiserver/v1alpha1/apiserver.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	v1alpha11 "github.com/e-conomic/proto/ssn/mlservice/v1alpha1"
	v1alpha1 "github.com/e-conomic/proto/ssn/ocrservice/v1alpha1"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScanRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02efc5d7626dab95, []int{0}
}

func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type InternalScanResponse struct {
	Ocr                  []*v1alpha1.OcrScanImageResponse `protobuf:"bytes,1,rep,name=ocr,proto3" json:"ocr,omitempty"`
	Ml                   *v1alpha11.MlResponse            `protobuf:"bytes,2,opt,name=ml,proto3" json:"ml,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *InternalScanResponse) Reset()         { *m = InternalScanResponse{} }
func (m *InternalScanResponse) String() string { return proto.CompactTextString(m) }
func (*InternalScanResponse) ProtoMessage()    {}
func (*InternalScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02efc5d7626dab95, []int{1}
}

func (m *InternalScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalScanResponse.Unmarshal(m, b)
}
func (m *InternalScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalScanResponse.Marshal(b, m, deterministic)
}
func (m *InternalScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalScanResponse.Merge(m, src)
}
func (m *InternalScanResponse) XXX_Size() int {
	return xxx_messageInfo_InternalScanResponse.Size(m)
}
func (m *InternalScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalScanResponse proto.InternalMessageInfo

func (m *InternalScanResponse) GetOcr() []*v1alpha1.OcrScanImageResponse {
	if m != nil {
		return m.Ocr
	}
	return nil
}

func (m *InternalScanResponse) GetMl() *v1alpha11.MlResponse {
	if m != nil {
		return m.Ml
	}
	return nil
}

type ScanResponse struct {
	Ml                   *v1alpha11.MlResponse `protobuf:"bytes,1,opt,name=ml,proto3" json:"ml,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02efc5d7626dab95, []int{2}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetMl() *v1alpha11.MlResponse {
	if m != nil {
		return m.Ml
	}
	return nil
}

type Page struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_02efc5d7626dab95, []int{3}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Page) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Document struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Pages                []*Page  `protobuf:"bytes,3,rep,name=pages,proto3" json:"pages,omitempty"`
	Ocr                  []string `protobuf:"bytes,4,rep,name=ocr,proto3" json:"ocr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_02efc5d7626dab95, []int{4}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Document) GetPages() []*Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

func (m *Document) GetOcr() []string {
	if m != nil {
		return m.Ocr
	}
	return nil
}

type Callback struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	HmacSigningKey       string   `protobuf:"bytes,2,opt,name=hmacSigningKey,proto3" json:"hmacSigningKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Callback) Reset()         { *m = Callback{} }
func (m *Callback) String() string { return proto.CompactTextString(m) }
func (*Callback) ProtoMessage()    {}
func (*Callback) Descriptor() ([]byte, []int) {
	return fileDescriptor_02efc5d7626dab95, []int{5}
}

func (m *Callback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Callback.Unmarshal(m, b)
}
func (m *Callback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Callback.Marshal(b, m, deterministic)
}
func (m *Callback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Callback.Merge(m, src)
}
func (m *Callback) XXX_Size() int {
	return xxx_messageInfo_Callback.Size(m)
}
func (m *Callback) XXX_DiscardUnknown() {
	xxx_messageInfo_Callback.DiscardUnknown(m)
}

var xxx_messageInfo_Callback proto.InternalMessageInfo

func (m *Callback) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Callback) GetHmacSigningKey() string {
	if m != nil {
		return m.HmacSigningKey
	}
	return ""
}

type WebRequestContext struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebRequestContext) Reset()         { *m = WebRequestContext{} }
func (m *WebRequestContext) String() string { return proto.CompactTextString(m) }
func (*WebRequestContext) ProtoMessage()    {}
func (*WebRequestContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_02efc5d7626dab95, []int{6}
}

func (m *WebRequestContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebRequestContext.Unmarshal(m, b)
}
func (m *WebRequestContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebRequestContext.Marshal(b, m, deterministic)
}
func (m *WebRequestContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebRequestContext.Merge(m, src)
}
func (m *WebRequestContext) XXX_Size() int {
	return xxx_messageInfo_WebRequestContext.Size(m)
}
func (m *WebRequestContext) XXX_DiscardUnknown() {
	xxx_messageInfo_WebRequestContext.DiscardUnknown(m)
}

var xxx_messageInfo_WebRequestContext proto.InternalMessageInfo

func (m *WebRequestContext) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WebRequestContext) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type Job struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Ctime                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Ctx                  *WebRequestContext   `protobuf:"bytes,3,opt,name=ctx,proto3" json:"ctx,omitempty"`
	Doc                  *Document            `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc,omitempty"`
	Error                string               `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Callback             *Callback            `protobuf:"bytes,6,opt,name=callback,proto3" json:"callback,omitempty"`
	ClientId             string               `protobuf:"bytes,7,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_02efc5d7626dab95, []int{7}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Job) GetCtime() *timestamp.Timestamp {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *Job) GetCtx() *WebRequestContext {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func (m *Job) GetDoc() *Document {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *Job) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Job) GetCallback() *Callback {
	if m != nil {
		return m.Callback
	}
	return nil
}

func (m *Job) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func init() {
	proto.RegisterType((*ScanRequest)(nil), "ssn.ScanRequest")
	proto.RegisterType((*InternalScanResponse)(nil), "ssn.InternalScanResponse")
	proto.RegisterType((*ScanResponse)(nil), "ssn.ScanResponse")
	proto.RegisterType((*Page)(nil), "ssn.Page")
	proto.RegisterType((*Document)(nil), "ssn.Document")
	proto.RegisterType((*Callback)(nil), "ssn.Callback")
	proto.RegisterType((*WebRequestContext)(nil), "ssn.WebRequestContext")
	proto.RegisterType((*Job)(nil), "ssn.Job")
}

func init() {
	proto.RegisterFile("ssn/apiserver/v1alpha1/apiserver.proto", fileDescriptor_02efc5d7626dab95)
}

var fileDescriptor_02efc5d7626dab95 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x49, 0xd2, 0x8e, 0xee, 0xed, 0x87, 0x36, 0x6b, 0xa0, 0xd0, 0xcb, 0x4a, 0x24, 0xa6,
	0x72, 0x58, 0xb2, 0x75, 0xe2, 0xc8, 0x85, 0xed, 0x52, 0x10, 0x1a, 0x4a, 0x91, 0x90, 0xb8, 0x39,
	0x8e, 0x49, 0x2d, 0x12, 0x3b, 0xb3, 0x9d, 0xa9, 0xf0, 0x6f, 0xf3, 0x0f, 0x20, 0xdb, 0x49, 0x1a,
	0xd8, 0x10, 0x37, 0xfb, 0xf9, 0xf3, 0xbe, 0xef, 0x47, 0xbe, 0x81, 0x33, 0xa5, 0x78, 0x82, 0x6b,
	0xa6, 0xa8, 0xbc, 0xa7, 0x32, 0xb9, 0xbf, 0xc4, 0x65, 0xbd, 0xc6, 0x97, 0xdb, 0x50, 0x5c, 0x4b,
	0xa1, 0x05, 0x0a, 0x94, 0xe2, 0xd3, 0xd3, 0x42, 0x88, 0xa2, 0xa4, 0x89, 0x0d, 0x65, 0xcd, 0xb7,
	0x44, 0xb3, 0x8a, 0x2a, 0x8d, 0xab, 0xda, 0x51, 0xd3, 0xb9, 0x51, 0x13, 0x44, 0x9a, 0x54, 0x46,
	0xe8, 0x56, 0x6e, 0x1b, 0x6b, 0x49, 0x5b, 0xb7, 0x2a, 0x1f, 0x80, 0x7d, 0xc8, 0x71, 0xd1, 0x4b,
	0xd8, 0x5b, 0x11, 0xcc, 0x53, 0x7a, 0xd7, 0x50, 0xa5, 0x11, 0x82, 0x51, 0x8e, 0x35, 0x0e, 0xbd,
	0x99, 0x37, 0xdf, 0x4f, 0xed, 0x39, 0xba, 0x83, 0x93, 0x25, 0xd7, 0x54, 0x72, 0x5c, 0x3a, 0x54,
	0xd5, 0x82, 0x2b, 0x8a, 0x16, 0x10, 0x08, 0x22, 0x43, 0x6f, 0x16, 0xcc, 0xf7, 0x16, 0xb3, 0x78,
	0xd0, 0xc2, 0x2d, 0x91, 0x86, 0x5c, 0x56, 0xb8, 0xa0, 0x1d, 0x9e, 0x1a, 0x18, 0xbd, 0x02, 0xbf,
	0x2a, 0x43, 0x7f, 0xe6, 0xcd, 0xf7, 0x16, 0xcf, 0xe2, 0x6d, 0x33, 0x1f, 0xcb, 0x9e, 0xf3, 0xab,
	0x32, 0x7a, 0x03, 0xfb, 0x7f, 0x94, 0x72, 0x69, 0xde, 0xff, 0xd2, 0x2e, 0x60, 0xf4, 0x09, 0x17,
	0x14, 0x9d, 0xc0, 0x98, 0xf1, 0x9c, 0x6e, 0x6c, 0xc6, 0x41, 0xea, 0x2e, 0xfd, 0x6c, 0xfe, 0x60,
	0xb6, 0x5b, 0x98, 0xdc, 0x08, 0xd2, 0x54, 0x94, 0x6b, 0x74, 0x04, 0x41, 0x23, 0x5d, 0x95, 0xdd,
	0xd4, 0x1c, 0xd1, 0x29, 0x8c, 0x6b, 0x5c, 0x50, 0x15, 0x06, 0x76, 0xc6, 0xdd, 0x58, 0x29, 0x1e,
	0x9b, 0x0a, 0xa9, 0x8b, 0x9b, 0x14, 0xb3, 0x82, 0xd1, 0x2c, 0x30, 0x29, 0x82, 0xc8, 0xe8, 0x06,
	0x26, 0xd7, 0xb8, 0x2c, 0x33, 0x4c, 0xbe, 0x3b, 0x41, 0xb6, 0x15, 0x64, 0xe8, 0x0c, 0x0e, 0xd7,
	0x15, 0x26, 0x2b, 0x56, 0x70, 0xc6, 0x8b, 0x0f, 0xf4, 0x87, 0x6d, 0x66, 0x37, 0xfd, 0x2b, 0x1a,
	0x5d, 0xc1, 0xf1, 0x17, 0x9a, 0xb5, 0x1f, 0xe5, 0x5a, 0x70, 0x4d, 0x37, 0x1a, 0x1d, 0x82, 0xcf,
	0xf2, 0x56, 0xcd, 0x67, 0xb9, 0xbd, 0xd7, 0xad, 0x80, 0xcf, 0xea, 0xe8, 0x97, 0x07, 0xc1, 0x7b,
	0x91, 0x99, 0x39, 0x9b, 0xa6, 0x27, 0xed, 0x19, 0x5d, 0xc0, 0x98, 0x18, 0x33, 0xb5, 0xab, 0x9f,
	0xc6, 0xce, 0x69, 0x71, 0xe7, 0xb4, 0xf8, 0x73, 0xe7, 0xb4, 0xd4, 0x81, 0x68, 0x0e, 0x01, 0xd1,
	0x9b, 0x30, 0xb0, 0xfc, 0x73, 0x3b, 0xf9, 0x83, 0x96, 0x52, 0x83, 0xa0, 0x53, 0x08, 0x72, 0x41,
	0xc2, 0x91, 0x25, 0x0f, 0x2c, 0xd9, 0xed, 0x34, 0x35, 0x2f, 0xe6, 0x73, 0x50, 0x29, 0x85, 0x0c,
	0xc7, 0xb6, 0x23, 0x77, 0x41, 0xaf, 0x61, 0x42, 0xda, 0x4d, 0x85, 0x3b, 0x83, 0xdc, 0x6e, 0x7d,
	0x69, 0xff, 0x8c, 0xa6, 0x30, 0x21, 0x25, 0xa3, 0x5c, 0x2f, 0xf3, 0xf0, 0xa9, 0xd5, 0xe8, 0xef,
	0x8b, 0x9f, 0x00, 0x2b, 0xc5, 0x57, 0xce, 0x10, 0xe8, 0x2d, 0xec, 0x0f, 0xbd, 0x8a, 0x8e, 0xac,
	0xe4, 0xc0, 0xe1, 0xd3, 0x17, 0x36, 0xf2, 0x98, 0xa1, 0xa3, 0x27, 0xe8, 0x1c, 0x46, 0xff, 0x48,
	0x3b, 0x1e, 0x44, 0x3a, 0xfc, 0xdd, 0xd5, 0xd7, 0xcb, 0x82, 0xe9, 0x75, 0x93, 0xc5, 0x44, 0x54,
	0x09, 0x3d, 0x27, 0x82, 0x8b, 0x8a, 0x11, 0xf7, 0xff, 0x26, 0x8f, 0xff, 0xf9, 0xd9, 0x8e, 0x7d,
	0xbd, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x11, 0xac, 0x44, 0x7f, 0x1a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SsnServiceClient is the client API for SsnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SsnServiceClient interface {
	InternalScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*InternalScanResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type ssnServiceClient struct {
	cc *grpc.ClientConn
}

func NewSsnServiceClient(cc *grpc.ClientConn) SsnServiceClient {
	return &ssnServiceClient{cc}
}

func (c *ssnServiceClient) InternalScan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*InternalScanResponse, error) {
	out := new(InternalScanResponse)
	err := c.cc.Invoke(ctx, "/ssn.SsnService/InternalScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ssnServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/ssn.SsnService/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SsnServiceServer is the server API for SsnService service.
type SsnServiceServer interface {
	InternalScan(context.Context, *ScanRequest) (*InternalScanResponse, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
}

func RegisterSsnServiceServer(s *grpc.Server, srv SsnServiceServer) {
	s.RegisterService(&_SsnService_serviceDesc, srv)
}

func _SsnService_InternalScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsnServiceServer).InternalScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssn.SsnService/InternalScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsnServiceServer).InternalScan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SsnService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsnServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssn.SsnService/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsnServiceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SsnService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssn.SsnService",
	HandlerType: (*SsnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalScan",
			Handler:    _SsnService_InternalScan_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _SsnService_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssn/apiserver/v1alpha1/apiserver.proto",
}
