// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssn/imageservice/imageservice.proto

package imageservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ImageFormat int32

const (
	ImageFormat_PNG  ImageFormat = 0
	ImageFormat_JPEG ImageFormat = 1
	ImageFormat_GIF  ImageFormat = 2
	ImageFormat_PGM  ImageFormat = 3
)

var ImageFormat_name = map[int32]string{
	0: "PNG",
	1: "JPEG",
	2: "GIF",
	3: "PGM",
}

var ImageFormat_value = map[string]int32{
	"PNG":  0,
	"JPEG": 1,
	"GIF":  2,
	"PGM":  3,
}

func (x ImageFormat) String() string {
	return proto.EnumName(ImageFormat_name, int32(x))
}

func (ImageFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f52ba60e79477746, []int{0}
}

type Image struct {
	Bytes                []byte      `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Format               ImageFormat `protobuf:"varint,2,opt,name=format,proto3,enum=imageservice.ImageFormat" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52ba60e79477746, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Image) GetFormat() ImageFormat {
	if m != nil {
		return m.Format
	}
	return ImageFormat_PNG
}

type RasterizePdfRequest struct {
	PdfBytes             []byte   `protobuf:"bytes,1,opt,name=pdfBytes,proto3" json:"pdfBytes,omitempty"`
	DPI                  uint32   `protobuf:"varint,2,opt,name=DPI,proto3" json:"DPI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RasterizePdfRequest) Reset()         { *m = RasterizePdfRequest{} }
func (m *RasterizePdfRequest) String() string { return proto.CompactTextString(m) }
func (*RasterizePdfRequest) ProtoMessage()    {}
func (*RasterizePdfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52ba60e79477746, []int{1}
}

func (m *RasterizePdfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RasterizePdfRequest.Unmarshal(m, b)
}
func (m *RasterizePdfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RasterizePdfRequest.Marshal(b, m, deterministic)
}
func (m *RasterizePdfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RasterizePdfRequest.Merge(m, src)
}
func (m *RasterizePdfRequest) XXX_Size() int {
	return xxx_messageInfo_RasterizePdfRequest.Size(m)
}
func (m *RasterizePdfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RasterizePdfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RasterizePdfRequest proto.InternalMessageInfo

func (m *RasterizePdfRequest) GetPdfBytes() []byte {
	if m != nil {
		return m.PdfBytes
	}
	return nil
}

func (m *RasterizePdfRequest) GetDPI() uint32 {
	if m != nil {
		return m.DPI
	}
	return 0
}

type RasterizePdfResponse struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Image                *Image   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RasterizePdfResponse) Reset()         { *m = RasterizePdfResponse{} }
func (m *RasterizePdfResponse) String() string { return proto.CompactTextString(m) }
func (*RasterizePdfResponse) ProtoMessage()    {}
func (*RasterizePdfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52ba60e79477746, []int{2}
}

func (m *RasterizePdfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RasterizePdfResponse.Unmarshal(m, b)
}
func (m *RasterizePdfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RasterizePdfResponse.Marshal(b, m, deterministic)
}
func (m *RasterizePdfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RasterizePdfResponse.Merge(m, src)
}
func (m *RasterizePdfResponse) XXX_Size() int {
	return xxx_messageInfo_RasterizePdfResponse.Size(m)
}
func (m *RasterizePdfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RasterizePdfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RasterizePdfResponse proto.InternalMessageInfo

func (m *RasterizePdfResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RasterizePdfResponse) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type OcrScanImageRequest struct {
	Image                *Image   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OcrScanImageRequest) Reset()         { *m = OcrScanImageRequest{} }
func (m *OcrScanImageRequest) String() string { return proto.CompactTextString(m) }
func (*OcrScanImageRequest) ProtoMessage()    {}
func (*OcrScanImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52ba60e79477746, []int{3}
}

func (m *OcrScanImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OcrScanImageRequest.Unmarshal(m, b)
}
func (m *OcrScanImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OcrScanImageRequest.Marshal(b, m, deterministic)
}
func (m *OcrScanImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OcrScanImageRequest.Merge(m, src)
}
func (m *OcrScanImageRequest) XXX_Size() int {
	return xxx_messageInfo_OcrScanImageRequest.Size(m)
}
func (m *OcrScanImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OcrScanImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OcrScanImageRequest proto.InternalMessageInfo

func (m *OcrScanImageRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type OcrScanImageResponse struct {
	TessHocr             string   `protobuf:"bytes,1,opt,name=tessHocr,proto3" json:"tessHocr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OcrScanImageResponse) Reset()         { *m = OcrScanImageResponse{} }
func (m *OcrScanImageResponse) String() string { return proto.CompactTextString(m) }
func (*OcrScanImageResponse) ProtoMessage()    {}
func (*OcrScanImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52ba60e79477746, []int{4}
}

func (m *OcrScanImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OcrScanImageResponse.Unmarshal(m, b)
}
func (m *OcrScanImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OcrScanImageResponse.Marshal(b, m, deterministic)
}
func (m *OcrScanImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OcrScanImageResponse.Merge(m, src)
}
func (m *OcrScanImageResponse) XXX_Size() int {
	return xxx_messageInfo_OcrScanImageResponse.Size(m)
}
func (m *OcrScanImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OcrScanImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OcrScanImageResponse proto.InternalMessageInfo

func (m *OcrScanImageResponse) GetTessHocr() string {
	if m != nil {
		return m.TessHocr
	}
	return ""
}

func init() {
	proto.RegisterEnum("imageservice.ImageFormat", ImageFormat_name, ImageFormat_value)
	proto.RegisterType((*Image)(nil), "imageservice.Image")
	proto.RegisterType((*RasterizePdfRequest)(nil), "imageservice.RasterizePdfRequest")
	proto.RegisterType((*RasterizePdfResponse)(nil), "imageservice.RasterizePdfResponse")
	proto.RegisterType((*OcrScanImageRequest)(nil), "imageservice.OcrScanImageRequest")
	proto.RegisterType((*OcrScanImageResponse)(nil), "imageservice.OcrScanImageResponse")
}

func init() {
	proto.RegisterFile("ssn/imageservice/imageservice.proto", fileDescriptor_f52ba60e79477746)
}

var fileDescriptor_f52ba60e79477746 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4f, 0xc2, 0x30,
	0x18, 0x87, 0x29, 0x08, 0xe2, 0xcb, 0x30, 0x4b, 0xe1, 0x80, 0x9c, 0xb0, 0x5e, 0x50, 0x03, 0xd3,
	0xf9, 0x05, 0x0c, 0x2a, 0x13, 0x13, 0x75, 0x29, 0x07, 0xa2, 0xb7, 0x51, 0x0a, 0xee, 0xb0, 0x15,
	0xd7, 0x62, 0xd4, 0x8f, 0xe7, 0x27, 0x33, 0xb4, 0x84, 0x6c, 0x64, 0xd1, 0xdb, 0x7e, 0xef, 0xde,
	0x3e, 0xef, 0xd3, 0x3f, 0x70, 0x22, 0x65, 0xec, 0x84, 0x51, 0xb0, 0xe0, 0x92, 0x27, 0x1f, 0x21,
	0xe3, 0x99, 0xd0, 0x5f, 0x26, 0x42, 0x09, 0x6c, 0xa5, 0x6b, 0xc4, 0x87, 0xf2, 0x68, 0x9d, 0x71,
	0x13, 0xca, 0xd3, 0x2f, 0xc5, 0x65, 0x0b, 0x75, 0x50, 0xd7, 0xa2, 0x26, 0xe0, 0x4b, 0xa8, 0xcc,
	0x45, 0x12, 0x05, 0xaa, 0x55, 0xec, 0xa0, 0xee, 0xa1, 0x7b, 0xd4, 0xcf, 0x10, 0xf5, 0xd2, 0xa1,
	0x6e, 0xa0, 0x9b, 0x46, 0x72, 0x03, 0x0d, 0x1a, 0x48, 0xc5, 0x93, 0xf0, 0x9b, 0xfb, 0xb3, 0x39,
	0xe5, 0xef, 0x2b, 0x2e, 0x15, 0x6e, 0x43, 0x75, 0x39, 0x9b, 0x0f, 0x52, 0x23, 0xb6, 0x19, 0xdb,
	0x50, 0xba, 0xf5, 0x47, 0x7a, 0x44, 0x9d, 0xae, 0x3f, 0xc9, 0x04, 0x9a, 0x59, 0x88, 0x5c, 0x8a,
	0x58, 0x6a, 0xcb, 0x30, 0x9e, 0xf1, 0x4f, 0x8d, 0xa8, 0x53, 0x13, 0xf0, 0x29, 0x94, 0xb5, 0x96,
	0x26, 0xd4, 0xdc, 0x46, 0x8e, 0x24, 0x35, 0x1d, 0xe4, 0x1a, 0x1a, 0xcf, 0x2c, 0x19, 0xb3, 0x20,
	0x36, 0xe5, 0x8d, 0xdd, 0x96, 0x80, 0xfe, 0x25, 0xb8, 0xd0, 0xcc, 0x12, 0x36, 0x6a, 0x6d, 0xa8,
	0x2a, 0x2e, 0xe5, 0xbd, 0x60, 0x89, 0xa6, 0x1c, 0xd0, 0x6d, 0x3e, 0x73, 0xa1, 0x96, 0x3a, 0x2a,
	0xbc, 0x0f, 0x25, 0xff, 0xc9, 0xb3, 0x0b, 0xb8, 0x0a, 0x7b, 0x0f, 0xfe, 0x9d, 0x67, 0xa3, 0x75,
	0xc9, 0x1b, 0x0d, 0xed, 0xa2, 0xfe, 0xe7, 0x3d, 0xda, 0x25, 0xf7, 0x07, 0x81, 0xa5, 0x17, 0x8d,
	0x8d, 0x05, 0x9e, 0x80, 0x95, 0x1e, 0x8c, 0x8f, 0xb3, 0x92, 0x39, 0xdb, 0x6a, 0x93, 0xbf, 0x5a,
	0x8c, 0x37, 0x29, 0xe0, 0x17, 0xb0, 0xd2, 0x87, 0xbd, 0x0b, 0xce, 0xb9, 0xcd, 0x5d, 0x70, 0xde,
	0x5d, 0x91, 0xc2, 0x05, 0x1a, 0xf4, 0x5e, 0xcf, 0x17, 0xa1, 0x7a, 0x5b, 0x4d, 0xfb, 0x4c, 0x44,
	0x0e, 0xef, 0x31, 0x11, 0x8b, 0x28, 0x64, 0x8e, 0x7e, 0x8a, 0xce, 0xee, 0x73, 0x9d, 0x56, 0x74,
	0xfd, 0xea, 0x37, 0x00, 0x00, 0xff, 0xff, 0x77, 0x93, 0xc4, 0x75, 0xc9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImageServiceClient interface {
	OcrScanImage(ctx context.Context, in *OcrScanImageRequest, opts ...grpc.CallOption) (*OcrScanImageResponse, error)
	RasterizePdf(ctx context.Context, in *RasterizePdfRequest, opts ...grpc.CallOption) (ImageService_RasterizePdfClient, error)
}

type imageServiceClient struct {
	cc *grpc.ClientConn
}

func NewImageServiceClient(cc *grpc.ClientConn) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) OcrScanImage(ctx context.Context, in *OcrScanImageRequest, opts ...grpc.CallOption) (*OcrScanImageResponse, error) {
	out := new(OcrScanImageResponse)
	err := c.cc.Invoke(ctx, "/imageservice.ImageService/OcrScanImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) RasterizePdf(ctx context.Context, in *RasterizePdfRequest, opts ...grpc.CallOption) (ImageService_RasterizePdfClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ImageService_serviceDesc.Streams[0], "/imageservice.ImageService/RasterizePdf", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageServiceRasterizePdfClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ImageService_RasterizePdfClient interface {
	Recv() (*RasterizePdfResponse, error)
	grpc.ClientStream
}

type imageServiceRasterizePdfClient struct {
	grpc.ClientStream
}

func (x *imageServiceRasterizePdfClient) Recv() (*RasterizePdfResponse, error) {
	m := new(RasterizePdfResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServiceServer is the server API for ImageService service.
type ImageServiceServer interface {
	OcrScanImage(context.Context, *OcrScanImageRequest) (*OcrScanImageResponse, error)
	RasterizePdf(*RasterizePdfRequest, ImageService_RasterizePdfServer) error
}

func RegisterImageServiceServer(s *grpc.Server, srv ImageServiceServer) {
	s.RegisterService(&_ImageService_serviceDesc, srv)
}

func _ImageService_OcrScanImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OcrScanImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).OcrScanImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imageservice.ImageService/OcrScanImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).OcrScanImage(ctx, req.(*OcrScanImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_RasterizePdf_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RasterizePdfRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageServiceServer).RasterizePdf(m, &imageServiceRasterizePdfServer{stream})
}

type ImageService_RasterizePdfServer interface {
	Send(*RasterizePdfResponse) error
	grpc.ServerStream
}

type imageServiceRasterizePdfServer struct {
	grpc.ServerStream
}

func (x *imageServiceRasterizePdfServer) Send(m *RasterizePdfResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imageservice.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OcrScanImage",
			Handler:    _ImageService_OcrScanImage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RasterizePdf",
			Handler:       _ImageService_RasterizePdf_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ssn/imageservice/imageservice.proto",
}
